Path: flop.mcom.com!news.Stanford.EDU!agate!newsxfer.itd.umich.edu!news.itd.umich.edu!urkabox
From: Peter Urka <pcu@umich.edu>
Newsgroups: comp.sys.next.advocacy
Subject: Re: The Once and Future OS
Date: Sun, 7 May 95 16:21:03 GMT
Organization: Squirrel Bin
Lines: 32
Sender: preston@urkabox.chem.lsa.umich.edu
Distribution: world
Message-ID: <07May1621030321@urkabox.chem.lsa.umich.edu>
References: <3ohapq$h3b@gandalf.rutgers.edu> <3notqh$b52@ns2.ny.ubs.com> <3npoh0$2oo@news.blkbox.com> <3nqp09$r7t@ns2.ny.ubs.com>
Reply-To: pcu@umich.edu
NNTP-Posting-Host: urkabox.chem.lsa.umich.edu
Mime-Version: 1.0
Content-Type: multipart/mixed;
	boundary="NutNews,-a-nntpmtsonsguinrcfas,-boundary"
X-Newsreader: NutNews


--NutNews,-a-nntpmtsonsguinrcfas,-boundary
Content-Type: text/plain

> NeXTSTEP, NeXTSTEP, NeXTSTEP...

Don't you mean: "NeXTstep, NeXTSTEP, NEXTSTEP..."?

--NutNews,-a-nntpmtsonsguinrcfas,-boundary
Content-Type: application/postscript
Content-Transfer-Encoding: base64


--NutNews,-a-nntpmtsonsguinrcfas,-boundary--
Peter Urka <pcu@umich.edu>
Dept. of Chemistry, Univ. of Michigan
Newt-thought is right-thought.  Go Newt!

