X-Andrew-Authenticated-As: 4099;greenbush.galaxy;Nathaniel Borenstein
Received: from Messages.8.5.N.CUILIB.3.45.SNAP.NOT.LINKED.greenbush.galaxy.sun4.41
          via MS.5.6.greenbush.galaxy.sun4_41;
          Tue, 16 Jun 1992 09:46:49 -0400 (EDT)
Message-ID: <4eDT39K0M2YtMC_2lL@thumper.bellcore.com>
Date: Tue, 16 Jun 1992 09:46:49 -0400 (EDT)
From: Nathaniel Borenstein <nsb>
MIME-Version: 1.0
Content-type: text/plain; charset=US-ASCII
To: ysato@etl.go.jp (Yutaka Sato =?ISO-2022-JP?B?GyRAOjRGI0stGyhK?=)
Subject: Re: MIME & int'l mail
In-Reply-To: <gEJO+.ysato@etl.go.jp>
References: <UeCBvVq0M2Yt4oUA83@thumper.bellcore.com>
	<gEJO+.ysato@etl.go.jp>

I'm in my office now, so I can see the picture you sent me without
extreme slowness.  Very nice.  As for your questions:

The white space in your name was an accident on my part -- sorry about that.

The characters you didn't recognize -- in my From: field & my signature
-- are my name in Hebrew.  It's pronounced "Naftali Ben Shalom".

When you say that it isn't easy to do multilingual mail in MIME, I
presume what you mean is that it's a pain to have multiple parts, each
of them plain text in a different character set?  If that's what you
mean, I agree.  This will only be solved when the ISO 10646 and Unicode
folks finish their work and give us a "one-world" character set.  I look
forward to that day!  -- Nathaniel