X-Andrew-WideReply: netnews.comp.sys.next.misc
X-Andrew-Authenticated-as: 0;thumper.bellcore.com;Network-Mail
Received: via nntppoll with nntp; Sun,  3 May 1992 20:23:55 -0400 (EDT)
Newsgroups: comp.sys.next.misc
Path: thumper.bellcore.com!walter!att!linac!uwm.edu!rpi!usenet.coe.montana.edu!news.u.washington.edu!news
From: Mark Crispin <mrc@Tomobiki-Cho.CAC.Washington.EDU>
Subject: what's the use
Content-Type: TEXT/PLAIN; charset=ISO-2022-JP
Message-ID: <MS-C.704934477.377401575.mrc@Tomobiki-Cho.CAC.Washington.EDU>
Sender: news@u.washington.edu (USENET News System)
Organization: University of Washington
Mime-Version: 1.0
Date: Sun, 3 May 1992 23:07:57 GMT

Once again, Scott Turner drops another clueless and mendacious tirade.  It's
obvious he hasn't made more than a cursory glimpse of the MIME document.  It's
equally obvious he knows nothing about the specifications of Internet mail as
described in RFC-821 and RFC-822 [those *are* standards, even NeXT uses them].
However, it doesn't stop him from making any number of absurd, false, and
downright foolish statements.

He's just as clueless about the meaning of the Japanese word `gaijin', yet
that too doesn't stop him from making a racist assumption of its meaning and
proceeding on that.  この糞っ垂れ

When challenged to put his code where his big mouth is, all he does is go on
about how he is `too busy making $$$' and `does not have enough time' to do
so.  In other words, the standard retreat of the nasty little net.geek who
probably is in Programming I.

It's not worth it.  If anyone believes what Turner has to say, then PT Barnum
was right about what was born every minute.
