Return-Path: <ysato@etl.go.jp>
Received: from thumper.bellcore.com by greenbush.bellcore.com (4.1/4.7)
	id <AA05435> for nsb; Fri, 12 Jun 92 22:23:28 EDT
Received: from etlpost.etl.go.jp by thumper.bellcore.com (4.1/4.7)
	id <AA16354> for nsb@greenbush; Fri, 12 Jun 92 22:23:23 EDT
Received: from etlpom.etl.go.jp by etlpost.etl.go.jp (5.67+1.6W/2.7W)
	id AA10002; Sat, 13 Jun 92 11:23:16 JST
Received: by etlpom.etl.go.jp (4.1/6.4J.6-ETLpom.MASTER)
	id AA00452; Sat, 13 Jun 92 11:23:13 JST
Received: by etlibs.etl.go.jp (4.1/6.4J.6-ETL.SLAVE)
	id AA13778; Sat, 13 Jun 92 11:23:08 JST
Date: Sat, 13 Jun 92 11:23:08 JST
Return-Path: <ysato@etl.go.jp>
To: nsb@thumper.bellcore.com
Subject: Re: [95:taka@fxis.fujix] MIME and Header encoding RFC.
From: ysato@etl.go.jp (Yutaka Sato =?ISO-2022-JP?B?GyRAOjRGI0stGyhK?=)
Organization: Electrotechnical Laboratory, Tsukuba Science City
Message-Id: <gELh6.ysato@etl.go.jp>
References: <9206120510.AA06898@atrai.sala.sony.co.jp>
Content-Type: text/plain; charset=ISO-2022-JP
MIME-Version: 1.0

Hi.  I received a message from a member of i-headers mainling list,
as follows:

In message <9206120510.AA06898@atrai.sala.sony.co.jp> on 06/12/92(14:07:02)
you taka@fxis.fujixerox.co.jp wrote:
 |FXISの神戸です。MIMEとヘッダのエンコードに関するRFCが出ました。
 |RFC1343は、ほとんどmetamailみたい...。
 |
 |RFC1341(.txt/.ps)
 |
 |	MIME (Multipurpose Internet Mail Extensions):
 |	Mechanisms for Specifying and Describing the Format of
 |	Internet Message Bodies
 |
 |RFC1342(.txt)
 |
 |	Representation of Non-ASCII Text in Internet Message Headers
 |
 |RFC1343(.txt/.ps)
 |
 |	A User Agent Configuration Mechanism
 |		For Multimedia Mail Format Information
 |
 |RFC1344(.txt/.ps)
 |
 |	Implications of MIME for Internet Mail Gateways
 |
 |--
 |神戸　隆博（かんべ　たかひろ）		FXIS / Network Team.
 |					taka@fxis.fujixerox.co.jp

He says that MIME has got RFC numbers and RFC1343 is almost about
Metamail.  Where can I get these official RFCs?

--
Yutaka Sato <ysato@etl.go.jp>
Information Base Section
ELECTROTECHNICAL LABORATORY
1-1-4 Umezono, Tsukuba, Ibaraki, 305 Japan
