Date: Thu,  6 Feb 1992 11:51:37 -0500 (EST)
From: Nathaniel Borenstein <nsb>
Reply-To: Nathaniel Borenstein <nsb@thumper.bellcore.com>  (=?iso-8859-8?q?=ED=E5=EC=F9 =EF=E1 =E9=EC=E8=F4=F0?=)
To: Nathaniel Borenstein <nsb>
Subject: test of =?iso-8859-8?q?=FA=E9=F8=E1=F2?= in mail headers
Content-type:  text/plain; charset=iso-8859-8
Content-Transfer-Encoding: quoted-printable
Message-Id: <635263359947544690.21002.0@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0

This is an ordinary text message in which my name (=ED=E5=EC=F9 =EF=E1 =E9=EC=E8=F4=F0) 
is in Hebrew (=FA=E9=F8=E1=F2).  

There is Hebrew in the Subject and Reply-to headers, if viewed with metamail.