Path: flop.mcom.com!news.Stanford.EDU!bloom-beacon.mit.edu!hookup!news.moneng.mei.com!howland.reston.ans.net!news.sprintlink.net!news.ip.net!news.iclc.net!usenet
From: ross@iclc.net (Charles Halle)
Newsgroups: misc.entrepreneurs
Subject: I  DID  IT - I'm a New Entrepreneur  -
Date: 25 Apr 1995 20:51:43 GMT
Organization: HALLE ASSOCIATES
Lines: 46
Message-ID: <3njncv$1kh@castle.iclc.net>
NNTP-Posting-Host: shade.iclc.net
Mime-Version: 1.0
Content-Type: Application/octet-stream
X-Newsreader: WinVN 0.92.6+

FROM:
Halle Associates
Charles F. Halle

Here is some new information you may find interesting...

I am now a New Entrepreneur..

I recently became an Entrepreneur and thought you would like to 
hear my story.

Being retired, age 72, I was bored , and I wanted to contribute 
something to life.  I am a Ham Radio operator, but that wasn't
enough to keep me busy.  In addition, I needed more money.   I
have a Computer/Modem and was fascinated by its possibilities.
Then I heard about the Internet, the Information Superhighway.

I heard about a program that gives advice on how to become 
an entrepreneur using the Internet.  I bought that program and 
started to use the Internet to market the same program I was
using. 

It proved to be quite successful.  I did not get rich, (yet) but
my time was very well utilized and I did make about $300 per week
after using the program for about a month.  More products are
being produced, and I fully  expect to be able to market these
products successfully.

It proves that one is never too old to become a successful
entrepreneur. I am very happy with my progress and will continue
to grow in this venture.

If  you want more information about this program, please contact
me at:

                             ross@iclc.net                        
    
                                  or   

                       Compuserve... 71420,1642

You  will be glad you did !



