Return-Path: <rhys@cs.uq.oz.au>
Received: from thumper.bellcore.com by greenbush.bellcore.com (4.1/4.7)
	id <AA09077> for nsb; Thu, 6 Feb 92 23:18:13 EST
Received: from uqcspe.cs.uq.oz.au by thumper.bellcore.com (4.1/4.7)
	id <AA11919> for nsb@greenbush; Thu, 6 Feb 92 23:18:07 EST
Received: from solution.cs.uq.oz.au by uqcspe.cs.uq.oz.au 
	id <AA14540@uqcspe.cs.uq.oz.au>; Fri, 7 Feb 92 14:33:40 +1100
Date: Fri, 7 Feb 92 14:33:38 +1100
From: rhys@cs.uq.oz.au
Message-Id: <9202070333.AA25077@client>
To: nsb@thumper.bellcore.com
Subject: Test MIME message
Mime-Version: 1.0
Content-Type: multipart/alternative;
	boundary="New_MetaSend_Alt_220042694"


> THIS IS A MULTIPART MESSAGE IN 'MIME' FORMAT.  It may contain enhanced
> text, graphics, or sounds.  If you are reading this warning, your mail
> reader does not understand MIME format, and some of what follows may look
> strange.  However, the plain-text version of the message appears first,
> and can be viewed with any mail reader.

--New_MetaSend_Alt_220042694


Hi there!  Here's my first test message to you using my own version
of metasend.

First some piccys!!

Here's the icon for my newsreader:

[A part of type image/x-xbitmap was included here, but could not be displayed]


... and how about this little devil to announce the arrival of mail:

[A part of type image/x-xbitmap was included here, but could not be displayed]


And ... any MIME message wouldn't be complete without a little bit of
*richtext* to _liven_ things up. :-) 

Well, let me know how this goes on your end. -- Rhys. 

+   +=====================+==================================+
+   || Rhys Weatherley | The University of Queensland, ||
+   || rhys@cs.uq.oz.au | Australia. G'day!! ||
+   || "I'm a FAQ nut - what's your problem?" ||
+   +=====================+==================================+
*_

--New_MetaSend_Alt_220042694
Content-type: multipart/mixed;
	boundary="New_MetaSend_Main_1292627053"

--New_MetaSend_Main_1292627053
Content-type: text/plain

Hi there!  Here's my first test message to you using my own version
of metasend.

First some piccys!!

Here's the icon for my newsreader:
--New_MetaSend_Main_1292627053
Content-type: image/x-xbitmap
Content-Transfer-Encoding: base64

I2RlZmluZSBEZXZpbDMyX3dpZHRoIDMyCiNkZWZpbmUgRGV2aWwzMl9oZWlnaHQgMzIKc3Rh
dGljIGNoYXIgRGV2aWwzMl9iaXRzW10gPSB7CiAgIDB4MDAsIDB4MDAsIDB4MDAsIDB4MDAs
IDB4MDAsIDB4MDgsIDB4MDgsIDB4MDAsIDB4MDAsIDB4MDQsIDB4MTAsIDB4MDAsCiAgIDB4
MDAsIDB4MDQsIDB4MTAsIDB4MDAsIDB4MDAsIDB4MGEsIDB4MjgsIDB4MDAsIDB4MDAsIDB4
MGEsIDB4MjgsIDB4MDAsCiAgIDB4MDAsIDB4OWEsIDB4MmMsIDB4MDAsIDB4MDAsIDB4ZmEs
IDB4MmYsIDB4MDAsIDB4MDAsIDB4ZmMsIDB4MWYsIDB4MDAsCiAgIDB4MDAsIDB4ZGMsIDB4
MWQsIDB4MDAsIDB4MDAsIDB4OTgsIDB4MGMsIDB4MDAsIDB4NzAsIDB4ZjAsIDB4MDcsIDB4
MDcsCiAgIDB4OTAsIDB4YjMsIDB4ZTYsIDB4MDQsIDB4MjAsIDB4ZmMsIDB4MWYsIDB4MDIs
IDB4YTAsIDB4ZTMsIDB4ZTMsIDB4MDIsCiAgIDB4NDAsIDB4MGYsIDB4MWMsIDB4MDEsIDB4
NDAsIDB4NmYsIDB4NDMsIDB4MDEsIDB4YzAsIDB4MGUsIDB4YjgsIDB4MDEsCiAgIDB4ZTAs
IDB4NjEsIDB4YmEsIDB4MDMsIDB4Y2MsIDB4MDMsIDB4ZjgsIDB4MTksIDB4YmUsIDB4NmMs
IDB4Y2IsIDB4M2UsCiAgIDB4ZmUsIDB4MDIsIDB4YTAsIDB4M2YsIDB4ZmUsIDB4M2MsIDB4
OTYsIDB4M2YsIDB4ZmMsIDB4NDIsIDB4YTEsIDB4MWYsCiAgIDB4ZjAsIDB4MzEsIDB4Y2Ms
IDB4MDcsIDB4ODAsIDB4NDcsIDB4ZjMsIDB4MDAsIDB4MDAsIDB4MWUsIDB4M2MsIDB4MDAs
CiAgIDB4MDAsIDB4ZmYsIDB4N2YsIDB4MDAsIDB4MDAsIDB4MGUsIDB4MzgsIDB4MDAsIDB4
MDAsIDB4MDQsIDB4MTAsIDB4MDAsCiAgIDB4MDAsIDB4MDAsIDB4MDAsIDB4MDAsIDB4MDAs
IDB4MDAsIDB4MDAsIDB4MDB9Owo=

--New_MetaSend_Main_1292627053
Content-type: text/plain

... and how about this little devil to announce the arrival of mail:
--New_MetaSend_Main_1292627053
Content-type: image/x-xbitmap
Content-Transfer-Encoding: base64

I2RlZmluZSBEZW1vbkJpZmZfd2lkdGggMzIKI2RlZmluZSBEZW1vbkJpZmZfaGVpZ2h0IDMy
CnN0YXRpYyBjaGFyIERlbW9uQmlmZl9iaXRzW10gPSB7CiAgIDB4ZmYsIDB4ZmYsIDB4ZmYs
IDB4ZmYsIDB4MDEsIDB4MDAsIDB4MDAsIDB4ODAsIDB4MDUsIDB4YmUsIDB4MmIsIDB4YTAs
CiAgIDB4MGQsIDB4YWEsIDB4MmEsIDB4YjAsIDB4MGQsIDB4YWEsIDB4MmIsIDB4YjAsIDB4
MTUsIDB4YWEsIDB4ZWEsIDB4YTgsCiAgIDB4MTUsIDB4MDAsIDB4MDAsIDB4YTgsIDB4ZjUs
IDB4ZmYsIDB4ZmYsIDB4YWYsIDB4ZmQsIDB4ZmYsIDB4ZmYsIDB4YmYsCiAgIDB4MDEsIDB4
ZjgsIDB4MWYsIDB4ODAsIDB4ZmYsIDB4ZmYsIDB4ZmYsIDB4ZmYsIDB4MDAsIDB4ZjgsIDB4
MWYsIDB4MDAsCiAgIDB4MDAsIDB4ZjgsIDB4MWYsIDB4MDAsIDB4MDAsIDB4ZjgsIDB4MWYs
IDB4MDAsIDB4MDAsIDB4ZjgsIDB4MWYsIDB4MDAsCiAgIDB4MDAsIDB4ZmMsIDB4M2YsIDB4
MDAsIDB4MDAsIDB4ZmUsIDB4N2YsIDB4MDAsIDB4MDAsIDB4ZmYsIDB4ZmYsIDB4MDAsCiAg
IDB4YzAsIDB4ZmYsIDB4ZmYsIDB4MDEsIDB4ZTAsIDB4ZmYsIDB4ZmYsIDB4MDMsIDB4Zjgs
IDB4ZjAsIDB4OGYsIDB4MDcsCiAgIDB4M2MsIDB4ZTAsIDB4MDcsIDB4MGYsIDB4ZmYsIDB4
ZTIsIDB4NDcsIDB4MGUsIDB4YWIsIDB4ZmUsIDB4N2YsIDB4MWMsCiAgIDB4YWIsIDB4ZmMs
IDB4M2YsIDB4MWMsIDB4ODksIDB4ZDgsIDB4MWIsIDB4M2MsIDB4ODEsIDB4OTgsIDB4MTks
IDB4M2UsCiAgIDB4ODUsIDB4ZjgsIDB4MWYsIDB4MmEsIDB4YjUsIDB4ZDgsIDB4MWIsIDB4
MmEsIDB4YjUsIDB4NTAsIDB4MGEsIDB4MDgsCiAgIDB4ODEsIDB4MTAsIDB4MDgsIDB4MDAs
IDB4ZmYsIDB4ZTAsIDB4MDcsIDB4MDB9Owo=

--New_MetaSend_Main_1292627053
Content-type: text/richtext

And ... any MIME message wouldn't be complete without a little bit
of <bold>richtext</bold> to <italic>liven</italic> things up. :-)
<nl>
<nl>
Well, let me know how this goes on your end. -- Rhys.
<nl>
<nl>
<signature>
+=====================+==================================+<nl>
||  Rhys Weatherley   |  The University of Queensland,  ||<nl>
||  rhys@cs.uq.oz.au  |  Australia.  G'day!!            ||<nl>
||       "I'm a FAQ nut - what's your problem?"         ||<nl>
+=====================+==================================+<nl>
</signature>
--New_MetaSend_Main_1292627053--

--New_MetaSend_Alt_220042694--
