X-VM-v5-Data: ([nil nil nil nil nil nil nil nil nil]
	[nil nil nil nil nil nil nil nil nil nil nil nil "^Date:" nil nil nil nil nil nil nil]
	nil)
Received: from gunwale.mcom.com (gunwale.mcom.com [198.95.250.11]) by abattoir.netscape.com (8.6.10/8.6.9) with ESMTP id DAA18866 for <jwz@abattoir.netscape.com>; Sun, 30 Apr 1995 03:04:30 -0700
Received: (from jwz@localhost) by gunwale.mcom.com (8.6.9/8.6.9) id DAA08377 for jwz; Sun, 30 Apr 1995 03:00:19 -0700
Message-Id: <199504301000.DAA08377@gunwale.mcom.com>
Mime-Version: 1.0
Content-Type: multipart/mixed;
	boundary="bODY.pART.bOUNDARY.2"
Apparently-To: jwz@gunwale.mcom.com
Date: Sun, 30 Apr 1995 03:00:19 -0700
From: support@halsoft.com (Hal Software Systems)
Subject: Welcome to Ishmail

*************************************************************************
* This message has been encoded using the Multipurpose Internet Mail
* Extensions (MIME) format.  The mail reader you are using does not
* support MIME.  To display the non-text portions of this message you
* will need a MIME-capable mail reader such as Ishmail (support@halsoft.com).
*************************************************************************

--bODY.pART.bOUNDARY.2
Content-Type: text/enriched
Content-Transfer-Encoding: quoted-printable

Thank you for using <Italic>Ishmail</Italic> from <Bold><Bigger>H=
</Bigger></Bold>A<Bold><Bigger>L</Bigger></Bold> <Bold><Bigger>S=
</Bigger></Bold>oftware <Bold><Bigger>S</Bigger></Bold>ystems.


<Bigger><Bigger><Bold>Getting Started</Bold></Bigger></Bigger>


This message contains a few quick tips for getting started with =
<Italic>Ishmail</Italic>.  If at any time you have questions, =
feedback (positive or negative) or bugs to report, please use the =
<Bold>Comment</Bold> function in the <Bold>File</Bold> =
menu to communicate with <Bold><Bigger>H</Bigger></Bold>A<Bold>=
<Bigger>L</Bigger></Bold>.


If you wish to be added to the <Bold>ishmail-talk</Bold> =
mailing list for discussions and announcements about the product, =
send a message to <Fixed><Underline>majordomo@hal.com</Underline>=
</Fixed> with the following message body:


<Indent><Fixed>subscribe ishmail-talk</Fixed></Indent>


<Bigger><Bold>Mail Folders</Bold></Bigger>


Mail folders will show up as icons along the top of the main window.  The=
 messages in the active folder will show up in a list below that.


The <Bold>Folder</Bold> menu contains commands that allow =
you to create and open folders and to switch between (activate) them.  Mo=
st of the commands expect you to first select one or more folder icons.  =
An icon can be selected with a single click.  Several icons can be select=
ed by dragging the pointer or by holding down the Shift or Control keys w=
hile clicking.  You can also activate a folder by double-clicking on its =
icon, or by holding down the right mouse button and using the popup menu.


<Bigger><Bold>Reading Messages</Bold></Bigger>


The <Bold>Message</Bold> menu contains commands that allow=
 you to compose, read, save, print and reply to messages.  Like the =
<Bold>Folder</Bold> menu, most of the commands expect you to fi=
rst select one or more messages.  For example, to read a message you can:


<Indent>Double-click on the summary line for that message. <Italic=
>-or-</Italic>

Single-click <Indent>on the summary line for that message to select it, t=
hen use the <Bold>Read</Bold> command in the <Bold>=
Message</Bold> menu. <Italic>-or-</Italic></Indent>

Hold <Indent>down the right mouse button over the message summary line to=
 display a popup menu for that message.  Use the <Bold>Read</Bold>=
 command in the popup menu.</Indent>
</Indent>


<Bigger><Bold>Composing Messages</Bold></Bigger>


When you are <Bold>composing</Bold> a new message, you are=
 typing into a <Italic>Motif</Italic> text widget.  The ed=
iting commands used by this widget can be found in the <Underline>=
<Bold><Italic>Ishmail</Italic> User's Guide</Bold></Underline>. If=
 you wish to use your own editor, check out the <Bold>Editor</Bold=
> function under the <Bold>Message</Bold> menu in =
the composition window.


<Bigger><Bold>Customization</Bold></Bigger>


<Italic>Ishmail</Italic> is highly customizable to your ow=
n tastes and habits. The <Bold>Options</Bold> menu in the =
main window contains commands that let you specify custom beeps and icons=
, pick the fonts for your display, add buttons to your interface, and con=
trol the appearance of your message list among other things.


<Bigger><Bigger><Bold>Multimedia Capabilities</Bold></Bigger></Big=
ger>


This section describes and demonstrates <Italic>Ishmail</Italic>'s =
<Bold><Underline>MIME</Underline></Bold> (Multipur=
pose Internet Mail Extensions) capabilities.


<Bigger><Bold>Enriched Text</Bold></Bigger>


This entire message demonstrates <Italic>Ishmail</Italic>'=
s ability to display and send <Bold>MIME enriched text</Bold>=
.  Text can be:


<Indent><Bold>Bold</Bold>

<Italic>Italic</Italic>

<Underline>Underlined</Underline>

<Italic><Bold>Bold-Italic</Bold></Italic>

<Underline><Bold>Bold-Underlined</Bold></Underline>

<Underline><Italic>Italic-Underlined</Italic></Underline>

<Underline><Italic><Bold>Bold-Italic-Underlined</Bold></Italic>=
</Underline>

<Bigger>Bigger <Bigger>and <Bigger>Bigger</Bigger></Bigger></Bigger>

<Smaller>Smaller <Smaller>and <Smaller>Smaller</Smaller></Smaller></Small=
er>

<FlushRight>Right Justified</FlushRight>

<Center>Centered</Center>
</Indent>

In addition, text can be <Bold>indented</Bold> as in the a=
bove list.


To add enriched text markup to your outgoing mail messages, use the =
<Bold>Edit</Bold> menu in the <Italic>Ishmail</Italic>=
 composition window.


<Bigger><Bold>Pictures and Sounds</Bold></Bigger>


This section shows how <Italic>graphics</Italic> and =
<Italic>sounds</Italic> can be included in a message.  The disp=
lay of these components is through external commands that you choose.  Is=
hmail comes with a <Bold>mailcap</Bold> file containing li=
nes of the form:


<Indent><Fixed>image/gif;        xv -perfect %s</Fixed></Indent>


This line tells <Italic>Ishmail</Italic> to use the =
<Bold>xv</Bold> command to display GIF components.  If you do no=
t have the <Bold>xv</Bold> command, or you wish to use a d=
ifferent command, create a file in your <Bold>$HOME</Bold>=
 directory called <Bold>.mailcap</Bold>.  Add a line like =
the above one for <Italic>image/gif</Italic> and change th=
e command to one of your choosing.  Add the <Bold>%s</Bold>=
 token where the name of the file would normally go.


Here is a sample GIF image:=

--bODY.pART.bOUNDARY.2
Content-Type: image/gif
Content-Transfer-Encoding: base64
Content-Description: Our company logo

R0lGODdhHQGUAPIAAAAAAAAAoAAv/9X//////wAAAAAAAAAAACwAAAAAHQGUAAAD/hi63P4w
ykmrvTjrzbv/YCiOZGmeaKqubOu+cCzPdG3feK7vfO8vAMBvSCz+gkKjcsl0IYPNqHTKeUKp
2KwWaL1uv2BiFxkum3Xj53nNfqXJ7bic9LbO73hNXZ3v+yF7dn+DfYGChIhxhmOJjWeLXY6S
YJCMk5dSlZaYnEqaaZ2hQ5+boqY4pG+nqzWpoKywbq6qsbUps7S2uiO4e7u/H711wMR6wr7F
yRPHyMrODsyBz9MK0c3UydaG2Nna19y63ovgu+Lb5LXmkOiw6uPsp+6V8KLy6/Sd9vP4k/r7
/I78aQIoSeA7golcEVjIsKFDAkgeSiQgQMXEixURykh1/lFixI4MByQ5AfLhAI0xFJZk+LFk
RhQrG6LcSCqAyAETT4okIzKnzZEnBOjEKXGAUJszZeGaGECVxKZwWEx8CTTpil453xB1uLNq
iq1cvVpVIWziHo98pD4dm3JpUa1vvawA2/AkWydY0b7RKxeCgIYvMzC9q1SlSbiH+0J4uIFu
SMItyj51+vBQBMYbBkNmkTfxGMcEulbAnAF06M1XOzs8WzkthAF07Qpei5qsW89dQIumcLi0
z9ooJLfeO1xxA80YkAM3obou4rDGj9O+YFr2cjrNGUJlxFcsg6kalF/ndRv657jeF8B+i6H6
+BLCV9fpPuF38unvRWRf2DU3/vr6F/lWVH7kldcQa/JF9UBdDoWHH4HBGBjSc85Ft4BMDbZn
H4QexCcTZQlauN5CAZBmgXgcViEhfxROaKFNMpUYowXupdjhfhDNV1x6dcE444kP2mjMLDGV
tNti2imQIY0bCpmBh0XueNljsd1nopNDGhblf1MulERYTA6IZZZa9njTTz3RhySJSi45WpBj
VoDjdpFw+cCIL10pQY1xXgAli2mAZhkDW4mkwF89AqlnnxTgiGCFPCapAF3UNcmoBH+G1qKX
rn0naZuPKermpY2umCNx5vn1o4yfTsAnqZji2J8VgnY6aaus4trlqLBGMCeIkK65Upgm9bqM
rJue/mpclBegaGwDjuqY6oJFWhfBq89Ci2ygahJqGnu8wRnBUWNGi2qw1BLwGq93WiqBuuVu
e56U0rGZrr0ALnrtafESORkodnqKL6FcUYDtuAPbmOmsT9SqIKjw3htxvuyuq2m/ZbIkLbre
Jiywrg0cPGWcCyc7aKHvriqsyl1aq7Cpj7ro1YH7shyyu+mSLK9/9F4Iss+hpqxvuoZi+SvA
njWAqMcfX1xzsRQsrbOpDCPhsFxgUcx00z/fzN/UGXN6rsxe8/v01reKGe7EQpbMbc+5vhn0
yl1/7HKK5qYRcK53E2yzejj7jXZ+rqAZYH8/ZVW0TjLdfdSIVKqHlHs6/tn0uGNFO8lRkS2V
BLGeK2W0ZVFDExj2RZ2D9DmvKxk6eutgVxJl6h2trvKwtr9eMYQG3YMGA+kZ3fs32e4w/DnF
93D8MMkrvzzzzRv/fCnRozJ9JNXzcP3D2Vu/ffc+fA++9tOPf8Ty5oePfvrqG8T++e6/D78+
8s/vTv1F2IO/GPLsn785/vufOGJwlMCEooD90IYMssYEBLJgaV8rAbmW4I0Flo4HE1LL7jpQ
N/IxYwYhIUrfetDBEGwlbiQoYQ6iQYMRCQFkRnHcSSoimxk6wCiTMmAAEBhDBkDwARNU2gxH
6LW0sY2HOnycA6S2RBs28VA11CEUQXAMGyQJ/ldgcVlIHtMqyEUQaCdhCdC++DkHaIdtuwJV
vcJoNh+1alQFW+MWyVhGFeHiBidkVdkyOEbxzJFtZ/yUm6T2xkS5KlRiIZEY+9hGNznGjCZZ
lbhKVTgcdO2KA2OQIslIFFBZh4uZHFgnfVSvwQmuZmzsmBoFVq82QTI0f5zYiNpERF9VEgd5
XBMbAcmmQKKRRYVUVy49KR27kLFxwbMbkmCUOT0ipZWslJG1WIIoN0Kzlsf6BAbRhkleasqX
mRslH1m1S2gC7krjrEAWqRXGVzotmoz8JYk6uRWgOKcDNeHBMF+ZJm+qEVdfC6Yb7UlHcDkT
A1+iox7b6EkthhJM/kBz5T7diM1YHYSEvXzoKsG4UE5mtJEB1ajfKjdNhV6LXC50p8Xk6c/K
tZKeIGOIFOV00R7kMZjljKYvIdnPl+JUOpIzp9xEwkTBQSRkEYXnKu+GyZxKbpfN9JM0iMBE
gR6UmOD0GzE5atVz3oRFHFWUEe/lNaduVI0i9KkwFznQam5gqkbQpLXSWtCPXpWWd1WOJE/T
VXU2dWYeC6k/RzpKna71oUUl06CI8Eh3JgyU6pobaEpJszFS9qEVPafN5rY6lXKtKtqh60P/
lk3qGQFl7eKsM3daTM6esIucZZ0pb6japO4RjbNsmkPhNU+AkpaSizWCELCpE688DgAoRn3m
OdUjFru41Icj7JsSNUDEvz33hq8ZVw0Jda0IBVcUYLVAMnNQW+BRgnuryKwUgigHWwVwDuN9
r3znS9/62ve++GVFAgAAOw==

--bODY.pART.bOUNDARY.2
Content-Type: text/enriched
Content-Transfer-Encoding: quoted-printable

To view this image, click once on the icon using the left mouse button or=
 use the popup menu available with the right mouse button.  To hide it, e=
xit from the viewer application, shift-click the icon with the left mouse=
 button or again use the popup menu.


Messages can also include sound-bites in the <Bold>U-LAW</Bold>=
 (Sun .au) format.  If your system supports this sound format, they =
can be played using the <Bold>showaudio</Bold> command pro=
vided with <Italic>Ishmail</Italic>.  Here is an example:=

--bODY.pART.bOUNDARY.2
Content-Type: audio/basic
Content-Transfer-Encoding: base64
Content-Description: A famous personality speaks out

LnNuZAAAACgAAEJ5AAAAAQAAH0AAAAABbXVjaGJldHRlci5hdQAAAH5ueW/+fGrva/Fr+Pp4
6md7dGTu+Xbj6ejw6+f89ft+/n71dXRtd/5x/m919HD1bvJ3+fP1eW7raulv9fl7fvv89nn2
7271fGzye/719n3s7nXsb//xbPBsbXxg9m1w8Px65Xn3evJz+vZ+7nLu//vqZux0fHt2d3L0
ePhu+/91+fV09fV47Wrtd3zqavh+dXtu/m1x/Hr0+eb77e367nz89nX//W9s9XD3de96+/dt
7nf+cPVxfHp4dv3xdHpw/nR0937yeOhu73r07XDhauN89/Dv+P9v8X1weHZ5fGn5bnJ+dvn6
9nvv+X797353+3jw/Pr98Xf6eXj7bvpxfHhufXp0d/r3ae5o9Ptx73jxfXfseX7y/n7zd+36
8/P54HLne37vaPRudHxr/nJu9nF492bucXnrZ+Zsd/v9+Hn6/Xxzfv/59v/u8+z85vd78m34
fn3vee538nl8bfhn+25peWl+cm3xb/B28H5/+Xrr//r98n3te/T5+e/+/u9t6XTvb+98+P1r
+HB4fXV2dHp2cnl6bf55b/j78G/xcvzs/u3y6+3v7P7tc/v9fWv8cHh9cX5u+W79fm9zeHr/
eP16fn37/3rza+Rs7+x15Xv06v7w7+r4+HLtbPJt8e5+8WjqX/11bH9rbvdo+H37/Xz183Ps
afb0a/to83h89XX8+mztdH/uee3u/Ox27G/ubvr7evL6bfl6eu9y73L47XPscvp9b+pu7fJ3
7vZz9/pp93R9bXr1Ze5refdl+GbuXu14efH28Xnlbu18/fN55n326HTq/P/+9Hnye/Jwfepy
5nr6+3z7fGt7aG5vbf5w+3zwefR2+/R27Hb9f3R7evp563D1b/p9ev34d3H+dvR8bv9zfnl2
73ftfv74+Pjr8uz48e96+/7+fflxdnr38/V/cO1ha2xudvhp+XN0+PjmcHlrc/32++728+v1
7nz3/+7teu989fB66/x19GP4aXp2bHlv9HDvfv12+210em96/f/5+/N97P7wdPV49fNs7f/6
63nrfnLtdvn8c+/7fXhu8G7tbXb5//xs+mxz7f317XX2/nx8bvRn9ndp73n7+f72cX52d/z2
aex39+x5527s+/vu+/b1+nr7bH1ycGV2bnR8+fN56Hvs8/7w+/N37fz4+PZ+8/bs6v7yeHhw
YHlib11yY25lbHf0/e/98fH+6O717/Hleux27fR253nxffT3d/zvfXptbn1p+2X4cmT/Z+9r
+X/8ff949Hj7+PXz/fvw9vB/73j3e3L0cXr79u/45vzlf/R8bnpj8GxnfGt3+219fWnqb+Zn
/vtu5nPpfvHqfuRy7+x77n76+3t6/mn5YvhtZfBn9HX6ff5/cvZy/X358/bt8/vj8+vr/+p7
8Xn893B3enNucXtkfHB0emv+aHV9dXn1aO9n+/Nq33vr/e7x6vTr4vvp7ffqee3493fzaelw
/P5kcWRnZGVmaW5wamlteXPz+Pjr7+jl6Obm5N/x4Orv4vHq7vn8fPpsZ2deZGVgYWJbXGtu
aPb9eu328eXy5uze4t7q6On36/fu/W/zdGFvX294Z/96eXhzemV093j07/H88Pj99/bu3fHh
evDyavdqc3lfaGhfbGRrdXB/efHy6+Xp3e3l5+Tk9O36ePfte3pmX2hhY2NxaX1/+fT07f7v
7+7m6e/5dHdv+v/veHN5anFt+Xrtdnx6+PPo8O7pffJzbm9jfXx3/XF6b2/+fW3q+Ojs9u74
5nnx+XjxYvxndG5oeXN0b35nemt77e3t9nNz7ufh3/jm8v7jbPBz8Hxxd/xra/hseHB4dH1k
ZGVifHb87f7w8+9v5u/r3/Xm++/0eel39HZrav5r93D+/2/la3lvYHBpevX6bm34+ub05evs
7n1q727t5/rsfHFza3xge2r6/n1rWmtt8+Ht6Pnv7ujf7un2/+/6b2xebGb7fWt4b3Ts+u33
+d/3325ic2p9dnLx9+1vePtsamlqcm5vZ19y9PbrfuTh2dzh5ujs5uvy6n77+X/5ZmtqZWVm
bmdwXmRgZW7u7+d57ehy8Pd/4PTt/Hnx9f3odvv6a/Nx7296ZXF+c/14dW5z7ejr7Hdse37j
9+7t8+35bWBeX/bl6eRrYltkcPLu8ubw5ezc4fHi7uPq43n0/1taUlldd2ReW2Jqe21p+uve
2dbe7ujt4d3v4N7d2/D3ZGtpdXxyYFhrXGNta3Nf/fTmfOhremdg/Gri7fpxfHj53uP3dfXp
1drW8/Pzf991bV5pX2FZXWd173lsY2hz6/DzcWn0/P3ravrg4O7rdfT69PPq6uTo4OHta3Rk
al5aaXL3dlxaWFr2fN/e6OPs62R3497P2dz5aH334+Noclpf7GpmV1hfaXVtb3z6cOXY1dLi
9fj0euh+Z29Zfm3r92lodfdx9HhhamX57nBtbP3d3Oh3YWvr//xjaODg5uhu7d7b1+hraHD6
5nXvX29xc3R5XGRram9gYF1hZ2736vh3+vXk2Pzz3frm7u717tTc2vl6cPZv/fdvcXRVU2Vn
ZXv97PVvbl1j8frqdXPo69bs7GF13tvW6O/tb2JhXfnv5txiW2x16GJfYe/je2NXV19r7t/q
4WNy++Tc3uXqa/R46Ofw0uHa8V1qZPr9bVpcb3VraGtaYXzi5+x1YHpk7N/g19zc7Xhpavbp
+P9fdlj1aGvpd/1t8OT3/n9zdmxdcmtsXVtoVfdu1tLR3PLT1tDY6uHsc3VbXWZfXmVqfGJj
ZGhqeHR0am16/XBm9eXZ8vDt4dvX5OXu+OVpZHBhe2dbXGns7mJpdv74X2lneGbm8PnsYOfd
1+fk2drjY15v7edubfbv+m5manPw5OrvcXR6dF9ectrkZF1PW2jv7nx6ceHd2+dnYm7r+P74
6+nudmzw/+Xx6OV74PHl8XFqbHx7bmpyXVZn/W9gYObg6/Vq/t7n6evm3+nk8230e9/1Y2Bk
ZWtgWvhd/Hr6fmr4bm/g9efZ3uZnYeje1vJrYFpmYvN1Zm3z3uf23efl/W9pZ2dfe+LreW9r
4WJhYXVpYnVU/+Xe1+rd+NjLztTj+/r4Y11PZHh9bFZfVmliXV9j9X7ocHPu+f/d2tbuXflw
5u/vfPxn8Orc33D65Or5el/pYO9+aP5oaHLwZnp+3O37Wk9XceLi3uN76mZ549bO1dr/WVRl
dl9bX21eZlJe/tjV1dDye17o6OX3df/zbmhkcWh0e/p+ZllUWvp859vd0eVsbeDV1e/rf2tl
ZWx3YHdy8O917N3oaFtS8uHp827d+O1tX/3+6nhhT1Ro52prWH3j/+x23t/h1+nd39rd7G9z
bu9uXVJYbWr1Y1pnX+He19je1fVwc1doXmXc5OxnXuZ83e9j+OHV4PdOS1Zl4vxrYll5ZHBy
9+Xf5d/f3Nnf8OnX2tvc8u5r72Vk71ddWmBfW2xcYfBTb11jbVvsfGZ9Xtra1tPe7eTXxs7P
eGb2bHheWE9TXE9bZG7t8+Nr+eLa18vk7v/6cP7wem1eWF9jX09dXmnu8OR2bnvm2MvW6t/o
cnRy7Oj0/X9tbltvWP55ZmlW/d/d7f5lY37waW94bfHy4fHt7+fd3tvx6+rjbmFSVmHw6Xhf
cv/xZ/Lp49zc7OzvbGluZXzs8G5wV1lYYmDlz+PsZEpO2LzQaUNMycvWX0lqZltgV8e+v81G
R0ha5uzX6tnG1GNMQ0lOamLoxcXNemdTW1hL2r7CaUFQ28njQ0duzs7ldVxaV1Ps3u9gUtbE
2kk/Vs3CyeNueeD0X15Z3MrL6EtCSd7Ldllo49XdXFnh2G5s8fZeT2zn8v3w3dzkWFheZl/8
yMt1REp4b8jNWGVN38fiZklQ39TGzN3SVkdPXlB6wLq+TzM4UsvcUnHOxcpvRz5Qdc/O0XHy
bvZMTFHuyMLJ3thdX2J+339rbPjY6lRLbNXWan1n2c3bWz9IYNvE1nj7XVBV2vVcST/BrrpE
JyxYxbtebrWutlg0NETVydHc4MnM809CS37Jvb3E0PNfST9ARlFMTVFXWlZa8tzo58zExNLr
fffX1/Te0tDvTEZRadPO3+1bTEdGTk9OWWzazM9sVOrZzdHPyMnJ2eHfb1dOW977al9Wd1RO
Znnr63VlUlJTXeJaO82tuEsnLsmuuD00yKuu3zUySs7MelrgxcPNaElNXtTKy83c3ehdTkhb
T0FESG3X9l5S8+dmWWDb09XraNvS3XVi3c3Re1/y0s/rY2dsYk9MZPLb7lpe495oVfrIyu86
PruvulIvNFHSyunKuLbBXDgyPUxT+NnMzfJcSkVNatfDvb7H3GVRSkRHT1thfN/Z9FxY8dfX
4drGwM92XP/W2Ozq295tT0xaeOtvW2ZfWU9TWFhRVPPY4VtOa8vE8VLexMlQPtC1tcU9NDhD
58e4t7zJfj8xMztX0sjMztL1Sj5GV9/AurrC0mVQQz9ASXHp9fza3XdYVeHTz8/Hv8l+TlvX
1vxr6NTqTUNKbfNbUVp1WUhJVWBPVdPD3UVJzru/Z1nFv1ZFxbG03Dw4QUhM87itttBSPDU1
Nz74v77PaWFMPz1G/r+4vMXM4VVBQEtPW2J74NTf/e/t4NnazsjJzuX+7v9navbd3W9VTUtL
V3d9bV5ZU0xNUl7u3e313tHrbODRx8jUSkHDsL1aRmTeTDw/xbK73traSzc3PEv+6trW0HtJ
SVNY5s7CwszT5GBKRk9ZWmR83dfq9XPt2trVy87d/e7t8Pn23NzoY1dWWVdWWW9rX1xaV1dP
UVzp4XXmzdRn6snI2/jaX97Cydz231pDP0dsysnWzb3OSj5CQz1EW+HV097s7XpZYtvNztHP
2HZaUU9OS0xY7uDo7tnL1tfR09Hh3d3t92zo2vxybGljT09UUmJdUFVablxRVmF96Hfm0dj6
dsvMzuTeaHXCxNBg9uZuSURQ1+Ts4cfMcVBOT0BDRk5a6tza6+To29na0c/P32tYVU5QSkt3
dXB+6NjT2dzOxs/b39vZeftvePfx9nVhZldUVVFaX1dVT1xcWVtv8W7p4OLr3dLLztrP2mnI
xtRy+tPhZD4/bOZqYdjE4fxcWE9GSkhRZWFiXWx96tLMxsfH0NjkYFFQTEpGT15dfPXWz8zM
y8fJ1dnm52lq/WpnZW51aWJiXFlZVE5NUE9UWV1k7vXn3P7jz83VzNDY2Hjrxc/249jmb1xO
VV1bbd/q9ez9XVRUVFdSU2FeXWprefjo1tTMy8nU63lfWVRQV1NUXWJndOPQzsrKztja39/l
e11icHVmYeltbHZqXldZWVlVWlBOXmxbafHd1Nvc1c/O0NjV0Ndt6nb10n5XVlpnbFxd697t
dG1ZZlxiZlzo9HRtWFhgYl/l3u/g4ujb3Xzn2eBmaX1vc/thbvTe3u3o4t3e3XXx5uLsdmVe
YWNjWFVcZH5pcnRgYXN8dezf6u5z/eT68vV15+jp2ur/bv3s+HHzders39/l6P39cGN0eGpp
YWxkXWNrc1lWa/1kaGZ98uPh59/p5+3wd+763+Pp5HFn8+Hh+2/08/Xm73pr+eDk5V5bbF9Y
Xm79bGNfZW7t49rk7u3e4frx//78d/Prb1dcX2tnbe7g3+fh8enx+/J6WmRlZHfz+nlvb2Va
cHV9aPDi5XRp5uva7u3j29h/d3tnYW70+WteYmT5+eL/cvH13Nv+8Gr+5N73+Ot5b2pqa2Nj
WmNyaF9e/uT2au/z2+TY1OTna2P19d7p5n5aXHV1X2Bkel5dYGdwYn1y4Nnf8errX/Hi29rv
7O3f6P1tZGBg++72dFls52t3+XZ2bHfx+O314+vn+Xfn3uRza2Zv9u/s7GdVYmxudmZpWmtw
d+x26/T+9W/f2d3vaO7k29r4bXd96uZvXVJfXFzuePXe7mBf8vji3uDuXP3b1NpgW19lZXlm
Zmtx+dvV4Pp23N3bfmb1bW5id9zobV9y4/1WblhXX1fs3tzvcXxve/Dc5fF5V1zzcG/9bnTg
8N/b2+t3bd7V3O7n4XlcU1JbfX1kUl/e6vD7a+3t39ja51pfdOnsb3P6aW5nX+1qZnB0bOjm
7W/ycN3V6f9t3+Rz8+Pi5GZOVF5pYGVkevB/dPDo4eff2Nzk7Xjv7V9w7nj3YGn5fV9fYG/f
2uPxYWhs9+t3bPjr8mJabGlmV11k++jo4dp9cuzd1Nfz6Or872p78GZd+ezh3vTtZv3uY27i
cH5XYnVjZ1dh39/ob1dcbO3o6PX+4Xt/49v/Z9zU6G1YXXtzePvq6Xrm4OxqUm3e5HtkVlH5
7Olqb+rh3d7s3t/6+9/kcF9qXVpbWGT3fH5hWV743dz189/f3fh87/F553vv+OBqYGti4Pnq
7nJg/PJpX2D+2tt1fmpy6uv14t5rW1NZVV5ha3Lc3Ovb3+PT6d7lde3d7+B4X19TV2lmbVtv
7vzve+fqeWT6/Orm5u7/ZmRheu57bXDr3+pfamjk9ufR2tDwcWdu42VfXnRmc2peVllg59P7
92Fi7vd76t/w3+Lb3uHY/Gly9XBcW2dvbGFb+W/5Zm7tfXB47mlYXtfXaNXL49xx78zmVGPr
ZnNcZuVtVO/gflti2fplcl1eXlz1XvBnXNzZ69nv49ze4mh72NzV7mLvXXJgft90SXHVUltc
dPdjadHhaWXj29Vxcdxy3tvZamtsWFZqYFVNZNvt69pQeOVdxspxfE1rWkzI4FTm9M/SUvPb
Ze7T1uVnYmzaT2D0V9TMT2fjVF/MZ2HrUFtuYl9WXfTm3dLRZ1/x4t/b9e7k6uvwaWrNfF3Z
2V1f415XVlf/4nJjdfJbXk9Y7f7Uylhx1+fr3ezn2HTl101O29j53dZz1ndWbl5IZ3lPae1N
TuH6z+ta2t75zdJ04Gxha2VydeXT7NXX5+XtXldZXfpaXlpaW1z4Y+bsx8tU7NhgaNzga19c
4c5YX2Re2dT92u5L+NVWW29W+95cZ+1cc8t7Tt7u59nue9FWVcfOcvvz785oWeZhX+9KatdN
WGxWWHLM5WjK41vtalh77Gr/a/jXXXbTZWPa11lZcVr7dvfWet7Q62bKzG7Y31v9WVBWSEtZ
ZV/c40370ffIw/hvzONe/tpYV05MTmTt397bztjNztRdcHdXTU9GPkJNTlTq0NjBtb29t77I
yd1YTEU8OTc3OTg/TVVe2MzHu7e6ubm+vMLK7FVZRUNDPztCSz1F+UXcyU9vy1Tyz+nNx9TE
wMy/xtPe72B+YlNFPkE9QldXW93MxcLHwM3n2XFJTD83Oj47P0RKZdvJv7y4s7e3tbm9xM/S
5l1MQEJFPT9APz9GU0JJ2Et4xlJnzUx50OLMwcvDwMq/y/TY3l5wVEBDPz5FQUtZaNrFw8fB
vMbHy/FeVk09PTw4O0NJWfDSysO6vbi2uLq7ws7R7WJPRkdBPkI9PUtAOEhlQuHaROvMTdrP
7M3IxsO/zMHL09DvWGRUT09IR0NITmvZzsS/v76/xtXb9VBKRTo4OTg4PEZNa9fKwr67t7W0
tbrCw8zw32BMST8/RT08Pj48RPs+cNQ/Z8pKaMvf4cHF0b6/vsTJzuBb41lLSkY/Q05SXPvO
zsK+vcTIyd1vVkM7Pzo3OjxDSl911Mm/ubq3t7q6u8TN2GBbWUpHR0A/RT9BUEs9TvdG1W1K
3dhN7dvdyL3LwL3JxcvT4uxbW0lFREQ/R0pU59jGwLy9u7/IzuxVRz85NDY2NztDU/PPxr+6
s7SztLe8xcnibFRHPj8/PURFQ0ZWTVT2VEHi39vlVG7kZWzz48jAw8i8wcnK0X9pVk5CQEFD
QUNPVH/OwL65ubu/xdD5WEc9ODIxNDg8QVTrx7+6tbSys7e4vsnVXU9HQ0I/Pz9FTlBaX11f
al5fSUT33s5QTWvic/nnzb+9v7q6wsvd8GFORz86Oz5FRkte383Duba4ur3Dzn5NQTs0MTEy
OD1KZtrKv7eztLO0t77L2vBcSEBBQUNFSlpga3zn7mxeXk5MTkJBXOPKb1XtzsvO38K4usbJ
w8fkTUZLRT88PURLUVj+1MfBvLu5vMHN42RMPTk2NDQ3OkNTfdDBura0tba6v8jZ8ldLRkVH
RUxQZfHl3ubp9WRPSEhHSEhHQlvZv77Z7dXFwtL60r6/y3ljdWlPRkJETkxJUGrn19fOxb68
v8TK1fJUQj06ODY1OUFPY9rFu7e3uLq7v8ffYlRVTklISFNcbfvy4uboZ1hOS0hISUpIUGf7
a9vGtbLDYlH9ys5dTmbJvsV2T1FfYE5BP0hVamdXaN/LwsC+vrzCzfVNQjw4NDQ3PUle3cnA
vLi5ur3Bydl5V1JNTEpMVXXs3+Lt8XJmVE9MSUlDR0xUb3bXztjJw7u2v+1ERFDk0t7m2cvC
zedPQUJGTkxIQk1f28vOzMq/ubi/1WVTS0A5MjM2Pk1f4NbKwbu5u77GzNHkcVtTUVZfbfrt
c3N4+vxcTklIS01MR0pVc9bT1tvx1sO9uMJfRD1Ge9HNzM3LwsTPdUk+QEVLUUtKUmnXycjH
w8O+wM14Sz86Ojs6PUNKX+LPxcLAvr29wMjd/2NgX2ViYW15/O/3cWRWVFFNTktJSUlPXW7v
4uLX2XXMxsW802BZS1XbzsbCyszM1e5cSj9BRERNT1BXWHPXxsC/v8LIz/1XSD09PTxBQUpa
+tXLxMG/vsHFy9bjc2tnZGRvaGRlXmNdV1haWlBOS0hOVFpfc+3Rz+bWyMS9v+JiT0lm2s3I
ydnW3fFrW0tGQ0NHUlhebG/fzMe+vcLG0+5cTUU/PDs8QUhPbefVysS+vb/Ey8/Z7HpkX2Jm
dGxtdHRzYFxcV1ZSSElITVxlYW751dXbysjEv87wYExPbdjPxszY2ndtZFRKR0hNUFtaX2v4
0M3Ev8HAyNRxU0lER0E+Pj5EUWjsz8vEwMDExc3U4/n2d3ZsbHFueHt5eGVcVlBNSUxKTE1M
Vmn+19LXzsfEv8LU6V1SXPjazc3a5XxqXlhVTU5LTVZaZ27y3NbMxsDAw8/nXE9IREVCQ0FC
RVBi59DMxsLEyMrNz9Xg7v52du/4eF1bW2RnWVlQUVFNTE9PWV1s8d/Wz9PLx8bFy91sXExT
aevX0Nrk/mplY3RoZltYW1lZX2t14tzPysfN1u9jVVFHRFVVS0U/SGrqy8bNxsfPys3c29bf
1t37ZVpeXGR0X2VhWFFNTUhNTlFfZWvr3dXNzc3Rz83P0NjffF5WV2fz3N3f3+Hs6+9pal1b
UE9NTlVcanbr5tnV1NTT29nj9XJeXVZUT1BPWF5m8Prf4dzc39bV1Nfb693e3OHndmhfWFNV
VFRSU05OWltfZ2r0597Z5NXRy8vM1dfb2NjZ0tvkemdjX1lYWWBcUkxKSk9XYX1++uvY0s7O
z9TY2/Xxc11US0tLTlFVWV5p9+fYzsnGxcjJzs7P0dx4YlZWTk1MSk5NS09NWmJicn1z+3zg
2tLP1NPc3uHWzMrJzNrpdXFra2piWVBIRENHUVp183rv5NTQz87Q0tjd9GxYTktJSUpOUVZi
fubUz8zEw8PFysvO09Xf8GJVT01PT1dNTUhHSEtUWF1aW1Jl7NnOys3TzszJwr+/wsrZ7vh7
a2VcTUZCPj5DSk5o+X/n7NzMyMjLztXl/WpaW09HRkdNU11s/uTh0c7Kx8jJx8zP2dvd4eR6
XlhOUlJSTUxIR0pGSExPWGBf8dvNysrO1M/LxsDAwM3V5nbxe+zoeFVHQT9BSE9Ya2T69Xze
1cfK0tfg5vZtW05PSUZHS09db+3i1M7MxsXCw8jIzdLU2+j1ZF1WUk5LSEREQkFCREhNU11l
Z/7Wxr+/wszOy8vCvr/E0OJvX2VjaGpWTUI/PkBJTltjYvfr2dLMyM3O0Nra6WtjU01GRUtO
UVZec+LVz8rHxcPExsnOz9Te9mVaVk9LTEpHRUNHRUZKS1RaWGxy7s3Ew8HEzMzLxsC9v8rd
fl5XXF1jaVdMQkBARU5XZW7+bevfz8zNy8/W2ef8alhPRkhHSElPT1r23NHKysTDwsDDwsbN
1Ob2Z1tPS0pMSkhEQEJDSklPTkpSUVzey8XCwcnIycO+u7vCy+ZyYXR2b2dUSkI+PURIT1hb
cGnq3s/KysnSz9fe5WRbT0VHRUZHRkxWbuPWysnFxMG9v73Fy83m6PxhW05NS0dIQD9AQEVF
S0ZLVVhl3czGwMHIxsTGwL29v8rZfnJ3a2tdVk1CPz0/QkpOWHD87NvMycTHx8zR3O95WE9G
QEI/Q0ZKV2bo0s7EwcC9vry/w8fW3fByXlJPSUhHQ0E/P0VGS0lJT0xNfs/KxsbMzMfGwLy7
vcTO2Ozw6np/Zk5FQT1AQ0xSXVxr+OHUzsvKzNDd6HNeWk1JRERFR0hMUmzm18rEwMG/wL+/
xsvX0tjd8GNTTUpFQj4+Pj9EQ0lGP0Xzyr29yv5QVWvEs6uqrbXNUz02ODtHVGZuZlRPTU9c
68a+ubzG6UU8OTtASFfv2991VkpNW+TGv7/C0OV5/tvYz8fFyNxxWWFtXFhYVkk+OTxGZm9V
PVjLubPISzU2QNCuqKu21m1HRkA7RVTTwsXbTzs/R3jVysC9usHrSDk5QEhcZu53YldSX3vu
4uTOxMjM6P7p5dnb1NTb8G/9a2xnbnZbRz1AU3jZaDs/fMCwv0oxL0HHrq23xd7P3lJBNz1n
xLvEbEc/SFV54dDFvrzE9Uc7PEtYWFRQZunmaU5MVtzHyMvb59vb2Nbf4+3f2Nfjb2Vu5/5P
TEpUY2VPN0TqwLPZPC4yXrqttcfN2cf1QDs4T8m6us9UREZeX2Zq2Lu3vNJJPj9IVlZPTWXY
1fNJQlDuzMzW2dbQ1+X96dPU2uzu3+B9ZfjkbVJJTWzrRzlP3rnASC8tQciztcnHxcbRQzo5
Sc28vc7vWk5MSElo0b65u8htSUNJUk9OT/bU4FZGSl/h6e/ez8zS/W7e1NXf9drRz/lZXe7W
+1hPYf4/SPbPwGc3LjpoyLzFxrvAz0o5PErizcTGy81rSUJEWuDKwLy9z2VJREpHR1Lw3fRY
T1VnXmjt0cvX397R1fb44M3N9mn+5uBwXGT14V0/U83K4EU2Ok5bcdK+trvOVkJBSE9T4sTD
yuhnVk5NTPDEvL/M3fJrUkBAS2r4XVJWcW1ZWHDYzs/Y3Nfg7dvTzc/k5dbmX19o/uVzVlPZ
yW5NQT5IR0RQ1r2+yM7aeE1FS1je0dfR1eRfTVRg7NPPx8vX52RcUUtLUVtXWFhWYWxpb9/Y
2N/q39na2tbRy9rZ1+Ln+PTf+mpeYHx+V0pRV1hQTFT94un/4tPabV147Obre+TX5nNeau/w
en3f3e5kXW3veV1ZXWdhZXH28nZz/Onq7Ofg4N/q8Ozr7ufj3dzf5Orr9/Vvc2p+eXRsbGth
XVxcXmZx9P34dmxvbW9y9vTz+O/4fHpuZm17/vX+c2ZqcnP5/P7s6ubm7+7u7Oz37f3t6+Hn
7Pludfrw5ez49X3w8HZ1aXR89ez57n56bGtobXl7dvxvbWdmYV9gYGJsbXdya29x9/Dt+vf8
8fp3+fTo3+Po6ufk5Obr8uzm4d3teW52fezqe/1ue3n292lpY2RpcGpramhxbnNrbGNrcXF/
cHr+9/53+PDs5eXt7Pj07np+bHP67+95cV9lbvvu7ezv7OPk/Xd0/+/v6vby+v/6ePz9/PHz
fW5vb/x2dGhoffT8+G5reW/6/nZ+efx5cP538Hl9cXZy+fDs6/d6cX/77Pp4fHTvd35uc/13
/PLu8/bu9vd/e/f06uXp7P98+W3+bXJxc/huc2ljaWJue/Pp7e///nL/9/Ts7uzw/PP5+P5v
fPtz9m9sZmhrbGxvbnN99/rt7ezj8ert8ur18ebq6XZxa2Vxcf/h6vF3eGVpaGZud/Dj4HNz
bHP5/Ort5+tybHRqVWJz+Nrobmd07O7tfPLu7/B9bXNtd373+nLt8379dGpud/z2+/X/9/X2
6/R3/O7r3uPn9n1ubGdoZ2xf9ml2bGV5/Pvl9PrvdHl8emzkfnXcaPXv/ep96O/f//TrYm9d
Y29n72Ll3mXgeOznbe135nf+bnb++W7odPflbGrwbn51ZONb7GL9bXboX+d17+lj5P5v4HV+
b/VvXd/+bd956+1d++N4cNpz6OVw4Gn973Bd62v74udibf14+1/mWl/nb13eaGlt119hzGhm
zWNe3Fxd4Vf/7lXP9VvQXlfOemTQ/FrU6Vfc20jN0k3NY/zPSeflVd5vZ3DiVFvVbW3s7Hbi
bm7qVtlpVd5uaNVfS9R3XH7pYdtw4vBz1F3U5VXe60/IV07EV1DGWkq/ZEfD+UXJZk7CU0/D
VFjNSPzGP+DFRd/RRM/0SthsfOvuZerZTtzMScrqVdda3G9Lz1hezWraZ1Lc1k3743vdXuhe
/dNOXs1T6NxFztk8w9E7vexDyNhF1M1I1spGz9pEztpG389H68lMTsteTspjT8hkS8VfT8lP
dMhOY8hQcdRO1uVK3M9N+clC9cFUT9zh5+BQWc/XTmjfS8VrS8ha7NVM5OJbbfdd4dlJ09xP
zvZPzntb0m9m3Gn4bWTRVGTb8eV+WODMVWzgTuzKRVHN2lR7Y+bs+/ZLz85Bz9M/zNJOX81g
YNle7/f0+3Xb9V7g4mdlcu56X3Pg8W5X3NtH1cxHa9DicFpl2+ZfXm/P1VZf0dxR9uBoYt/Z
TFvU21Vc9O7l8E59xFhK6dbOV0TSx15JfNJ5cG95/dvfYOzcWnTPX1Tc5HZkYNncZF1y4+55
XFTcy1pO9PXlclDmxvdL4MnrTFLQyWRBWsPMT0Rzx9BRSOPJ3llL9c3qVU7jyntIU9HNZlFZ
2M16XWfa3fxv+Prs+vDw+Otpfmf/bGn4bH/7dHR7Z2t5bfT+/Pl6//1++Xr38f3offTt8Oz2
7vLu9vV4fHd6cHl7evl2b3xpc3N7eW73bvp5dfL+b+t9+u1v7vv75vL07vl99Pp37nj5c/xq
d2lpc3V78v14+vl0fPl2/nF+/3x//vl/7e/4/vbz/vJ06v/47nbwenH9+mV8/Pl9cupx8G95
/mr9aXz7bfV1/v15/fJ7/vrz+3/tdOhkfvts8vr/7e106/X47vn7efD97/Rs8nN3cvdva3hn
+2z6fHLz83xy83dtd31u7nxy9f7/eO1v+X57fPf+/Pn8+ez6/Xx+83z7+/z993L0dG/+bvJx
+O7/8vP4f/f0/vV2/PR79/Zt7HVwfWT4ZW7+Y3htfnVufm94//l89ezyf+z96/h/5vH16fTs
9Pl+cPN8fPv/9v7wfnH6dnxwb2pmbmt6fG/3cn7v9fj3633783nt7vn29O16fnl29Gf+9Gr/
e3B9a+1ma39r/nB36Hfu+vrxdPFt8v186vzue/Tt8vru7fT67vby9nLvd3Z4cHlybP5tfW12
dWr4Yvhv9nzw8/R6fn5v83T0+/5+7el77Hx+52fp/37s9ex3fu7+7W9o/nF4/XX6b331dOht
8W32+W3paf/taPNsd/Bq7nZ29W5x8m/vavD77u136ft35nHiefftcfl5dXlu/v91+G129m72
c/v4eu907Hr09XT2aHlxbXhsdP/98n589Xf38/rv8/rtefFwfXpweXnx/fbt6e748O357/nw
8v56fGlsaGdiZF5zbXB+afF17vr28ezl5e/q7e/nfOXt6u/77ml3ZmtucG5seGh9Zm5ubnb7
7XTt+vnvdutz5X/57vf6eu9x+P5+7u9+c3b97/Ts833vePz9fXprb298a3ZnbHlm93Pv6vfx
8utvfnnseOxpbvhv6Xfv8fnlfe79/vp2cWx2b375e29+dPXt8+v26O3v9Wz0bH/3b+t5a3ti
Z2xrcPzubfZu8Hr4de/v4P73+nn8e3v4+O3y3+9yemP9cXp0YXhyb/piaWRufv3s7GdhxNBP
TlvLw3BTZ83I/ltdbff89WRYWGzo8W5pY3vrauh0a+1rZF5fbm/iffDs6OT139bf6HNp6vB+
9u7nfWls/GxfYVr3eOfrd+/m53xhZf34XG1kXGf+2ubxY/3j23tvZXbf7Ol76tbT22dZ+PZt
YlZXfmtdZXXtfGTy3OXsedvR2uJn5+dvUVFXcXNbVWPx7vns7Ord3/Hk2/DqcPXs5vppfPfq
X1/f1epfZfHc5FBMZ3Z2VUrzy8ffYDs5vK29WT9IXkY1OtCussK+usdSNC41QUM/S826v87E
vbm8xsrP30hAPjo3OEJTXl154tLe7NHCvsnMzszWZVZa5uddTO3IzVU9RF5cT1BDOlW6qcQw
KjrT2UVvqp+qyl7lezQpLk3K117Mt7fPU2XR0m5aeORjSEVIST89P0xZX2nZxb/Ax8zKz+xm
Yeve4vbd0NHoaW7je1FNXWRWTk9YbFxQaFBI27yvxT04Tdl8SumxqrbsTF1NMSw1XcvV78i5
vvpGVtfTf+7MydtZTkxHPT1IUVhk28XDzM/Mztpq+ODpbXHYzdDj5uPpY1VVXFpWWWFYU1r1
WD5Xx7S/QTE97N1S/raqr85MTlE8LzVRxsDOy7/E50lFYtfV2MzEy+9NRURAPkJOaerf0szM
1d/k3eLg6+3s497f3Nvd8XRuXk9TXGttXVpcYGZFP3nBts49N0rU1V3Ys6u2e0NHSjozPP++
vc3PytFaQUV7z8vNycbPXEU+Q0dDR1Xeztjs6Nna6nHp0tDc59zT0dzk4uP4YFxXXGNcXmln
WWNHR+PMw9pBOURd6evLt6+21kpAQj06Q37CvsfO1+JaSEtm1cnHxcfSYEdBQUJBR1n93up7
593b4eLWz9Ll5d3Y1t/aztDfcl9iWlZQWW5hZ1tDTdrT5FY/P01OVta8tba+z25KPz9FVeLP
yszO2mtVUVn/3s3KzNx6XVVKR0RKVFlsduzf3tvZ19fP0dvb6ep9b/HZ1eVyde7/WE1SY2lm
aFpZ2uDq/UpHWU9TatzDvcbS61tOSUdMcOHZ2NDQ1+5o6M/P2dzOzu5bT1ZRRT5HU1pPT2zW
0t3d2NHX6vHVz9Tc29jW6Whm6eFuXVxuZGFUVFpe595eV11bZVtSZNPM2uze099+W1lu5vNq
bfjt/F9h59rj4NjYzeBxZV1dVFBQYGJYX29sc93a2uPl1uvc5Ofa2elr7uB2ZWFl6mrxZFti
aXN7euvr8Ht6cnJkYmJjcWdnZ3Zv8PDw4t/d5u36fmtoZGZ8cP7u6+zw5efn7PtzdPx3d3f8
6uV3+fTr6u7r9vR6bm1rb3r49f78dG5483xsd/nt5fBo+mRpaF5o/ODo9n939nttZ2BfZ2Fk
Ym7u+uf29evp6fBu9X70+/bq5uHf2d7e63/reWz07+je5/l2bGheY2ZebG5kbHr77Pr18Ozm
9f5mYVpiXV5nYWphZ3Pu7eLv6Of19O3k5Ofz6uLw3+B17HhnbnVue+j28m91/OLyd35+/Xtr
e/BsanPqe3L0/evxa/78c2BsZmVkdvPt6OxmcvDvefJvW2DUyENHSG+97drP2cxQW1/591TO
1MroXM1dTk57319ZSdjMZWX929lkTnhrVW3t3tH24dncaVX46Wtdbm/v1W9d0m1k+Vdse130
1+Ze32191Fpd3f/g8X/973FZ4W5VZ/vvfuv50dVkWubc8etHZdvrcmFtz9XuWnfuXl5LXW9d
Vfzf5v3X38/NW/DN323dztpqU1n9805LfXpRSPLSYlBxzsxcRuzD0llY58jdW13q/Vpv2Nte
dc7S+lxW3uRQSmToV09X3tHnadrCzFxa3t7iTE3jznlLV+njX1Zv2thlW+DsYl9o7vV/4tfN
blvw3/pd/PrZ0nhf8tnd7eJ6XV9LSVFaZmBg5t3qa/re2eF66tfN7V/+7fduYV/u4uZ55tzb
9mNUVWBeZl1p/vtoYnXm5drc2/FcZvZ89vTZzs7pXerYf1ZQ7Nr5VE9p6GlPXN3fX1do3fxY
YevX3u3n19BvV+vd/VRo39neYvDPzuZY+c/uT0hPYV5MSmrb71xY7t3ubmDJwcPyVP/z/vJo
b9vR12Zm/3x1T0pZ6WZUYf3Ye2Vc9M3U28zJytpZTl1iSkVJTlJUWvzSztXKys3g+np73m5Y
aH1oZVxq19NzT9nO2mtOaXPnTUhg1NdbZNLF1GtYaftbSU12+1tT58nGwb/AwMx3T1xdRj89
QkI9QEdeaXTez8fJzc3IzNfTz8/Z7Hno295oaWheX3xZXdniW0xIR09VWFjZyM3Q0MjLzeNk
aXRSREVMU0la4drcycPDz9HP1PhIQD9HQj1CWmVTZ9bIxc7X08jHztbNys/Y5+vi3OVydlZX
Z+9aSElDWtPcU1FcX05ESVjV0NzRwL7OXd/fcVdTWlpiUE1Q+O/gx7y/xtDed1JHQEJFQkFL
VHV8b9jIw8jMyc3M0OTaz9rZ1+bnYmloWlpOVllvX0pJVF5VVNnM32Rr19xNQk3Xyd7myr7O
WE9dbltITlz+Wk5d5M3NzMzDxsbT7WpMSEI/Q0xOW2js8+Td2MvMzc/JzNHY7d7+dXnU2N9k
WFFOT0pdZGdPUVdWTExe2V5Nz8LHclRq3v9VUc29w87Kw9hdS0lOTEZGSVdeW2zp0cS/vry7
wdH3Tk5HPjs/UFhOTFl23ebc0sbI09jaztbfedra2GT30druTlho91NOSlVPTEtJVVZb/tzf
8+lnyb7IaFTzbU9GVd3Dx9vMw8p5Vmr7WU9TXF9nWGLu19LNwsTKzd32VkpPRUJAQEpaVV95
595v29fMyNHd2s/M39x19d793vjm/HhcSldbXF1PTVpJQklRdG1q9s/L1tLL3sO8yM3T1u5f
TEZv1e9Y6NPZW0lUS01FTmPh29/i53Fl48vAytTc2NprSkdITk5UX19gdPlzZV/dz9Ti4c/R
2vJ+2dDNzs/uZGlgVU5LT0pGTktOSUlZcH186M/IzNDWzdDIyda9vc/oa1ZPTUZP6Nri9N3b
Y1NSSkxNTVRTXWt9cP3Z0c7LztLP1d7wXVVLTkVFTk5fZHTt3NjdzsfFxb2/xtltX3RuVllj
cWNPT0pLTUZOU05RVlpXV23bztHXzs3Ixs3IzNDPZWDNxst3VVFmTkFJZs/vVVRYWUhPX+Xd
U05daHVr487G0vDcy8nM1cnbeU1AR0VJRklLWGHs283LzMrPzsvIyc3Y4u3wdWVxblJOTk9K
UVhRVlldWlpjX2hrcOPi4tXm1NTh0tXO19Xe39zT4OreaGhnY1n532ZfV2psVW1tWVpNSkZK
TllzeODV5d3X18rHyMnP3O1mW1laV1xbXFRNXXXz3s/Pz87Sz9DT29vwbVZdV1ZbVm1ualpP
T0VJTU1YWF9lX+nc1MrMxL7Bw8vMzc7Y8vPm311XW0tLSURNU1RSW214ZWZ0YXbj69ny+/hq
fWvyc+PT08zn3t7R1OX+Yl9XXVVQSUpNXu7q2tfW0M7OzczSz8/U2u/yblVPV239Zl5LRUBC
VVRXVExOTFNW7dPJxsrHzcrHyL/Exs3S1N3ic3RZVUdESU5PUk9mXVtOWF1nW1tYYVpXbG3e
5tnNxMLBxs/X7N/zbfpbUVFRTlpvdN/c2dzW2+7i7dnNytLsZVBMT0xMUV9PTVFNXnP57O5l
XllUWF3+3NHJyczLzMrGysfT2P5iXFBt19fr4GBKSEpSZmdWUlJTTlRUYWNbVlZed3rr7uTW
09PLvru8v7/J2v5pYVdJQkRFPz8/S2rk2s/R1tHYz87c29/f2/z0ZmdwZmlXVU5PT1JZYGFj
Z2x29O7f5OPf0tbe3dnP0tLP1c7S9Vxe/19dWFlZUk9VZX9YT1L97WNdYGJgbGR26Ozc5OTc
eebiy8C/vsbK0WVhWllTSEY8PT5DVG/T0M3Lz83T0szRz9bo32pfYFxiVWhZWFhNT0tMTEpW
VlxcavnbzcfLx8vJxMbFytjb7Nvy7mF83mZXT09OR0BGRn1uV1BTb1xXXfXN2/5qY97Z1tvR
x83R1M/Fys3h5PlPUGpYSkFFXWVHRFPc0GB8y7/IfFvQxNBqbNTN/U5Y3dZsTk5eU0c/Q05Q
TVFlYH38fs/Pw7/NxMjN4djEu8lu7+3TyN9PREdFRTw5Q9rMaFFpdFM/Pl7OyuTl2NRbTU31
yMK8vbzF2mxcWUpLYf3tfFBj2O1HSuTGyF1S38nZS0rZxs5eUnTlZ1BZ+X1TSklcWkhKUlxq
ZePRzczUzs3Q08fEyOh5xsbuW19efcPVUDs9Q0lAPFC/tNBSbsdlOjND1MN9TWzL3EdHbMK9
wMG7t8D8Sk1dTklSWv33WVVBQE1q1NnTy8DIaGBq0s/dc+PKyvBJSlJTRkJIYXJQSkZSW2Ln
1M3e3uLOyczSysHX3cbTXmLfxb/sOzjJu/A8NktvVDI22bm6Ykdq0N5HP1bLv9hceeTeX1Zf
2cG/wMbPd1NOSUZOZOnb52dr1eVWSlvLv8VhV9rM9kRCYsvMZ1Z7z91ORk3+aExJXN/uUUhT
6dLW5trMytPu7tTJydRu5MPM5EI8VszDYjg8xrbHPDBC18hFP865u3VARF1pSUJlyMDXWFlu
7e3228W7vsjZdl9TT1Bh7WhhVk9U/OdXU1zTxcv1T+rS3l1PctPab1Rd7u5wVVllZXZ2W1NV
ZW1ea2fcz9jf69jLzM7P09DXeujffl9LWeHdZEhASd/D1Es6Q2frU0Fnv7e/8lhbbV5UXXzX
2N/obVFITuTIwcTPzc3bd1tfX1dYZW1cT0hc1m5ZSmfKyMxwctXr91ls2NnjZ2nn81RGSl9z
a1hRY/tuVVb73M/QzsvP1+bcz9fg7d/W/V9aUfFzW2du6ktN083PTTk/atpnWdTDv9tNR0tY
UU1Y4c3M2+dpavbp0MjDw8jO82FbV11VWF5qXltaVmhaU2jezNbwX/fZ3WBSZdrN8FlTddrl
XVln4OBqXlpnXlFVW/rc2Nfe4PPr4d3Xzc7b19ff/1tWbHFfZ2pZTP7Jz+lDQ1BZWk3bwcTc
V1VcXEJCT9O+z+tXaOr67XnVwr6+xs3oWVROT09LT1hoZFhPWWJo29vV2+XV1df+Wmjl5+p+
Z/P46fFfX1ZYaXr4Y1NVXnBdVmDYydZ0XufNzdLf4MzFyWlWYPPSc1FSWV3hyN5TOj5MYOtN
YtLJvtB+Sz9DTGnXysrmc/Zpa2dz18W9vsLNfVdPTVBOUl9v/1tcU1RlZ+LsfdvPyc5vXFNf
cX7x+mxr7d7fXUxS7s7QeElMYevhdmRb/tXN0ndUVOXNzdh82c7T3F1W3tvO5lJPQ36/3ms5
NlBP6U9RxcbB2ldcSkxNWuHO0tbi6GtVc9/EwMbFycnVaE1LUVhbWV1TblRP5F1bTVTLyMxw
Tt3bc1VJct3Zak9h7tfuaXV82Nff+F9jd2/k6vV/a/P54etucXvazdDabWTx62dr6m5rUV7Y
cU1mec3XSEE9VHJjzsO/xXtNSVBVXXPcztjZ7mVfVnfkzcLCwMzefFZPTlJVXF1pVlBOSmfo
8XVf2sbH209Le87P3VdZfeDffGp3bmlzZ/hhUE1U9uLyXWHr1dPf4vLZ1t7d4t3e7mnz/eXW
/GZUWWvjZVfm6878Q0I7RmftwMbM22BeVE9UXunOzNZuVFRheOPVysG+ydd7XXplZFlWYF1a
TlBTZXF232lvfXz4YFxo787O6XJcednV1vB/9fDsZFlcYGliXGj54d9wYl76183P42ZaaN3T
4VpY9dXU5FNMX+bk18vv5k5GS0FYUnnJzMrWa1pLSUxc3srIz9fyZlhUetnIwsbP4fhtYFNO
UV//X3RbUlVJUHnax+x/ZmLi7+7669fb3uDl2vdhXX7a43BVXHhuTUBEYtnP4V1ebt/XzszQ
2NjZ29LfatzkX/zs5XpQS0pP69rZ6Ec+Pk19bWpv2si+wPdNRUxu187d5OLg4XNdWPjPxMDI
z+xuaHVpUkxMWFlcTkZOVeve3tvv5+vl2Nvl6N/V2vRmXP56Y19d8entbVFTVl5t/fHp7eDf
4PZ4+/3a2trr2tDZ2nhWYNrP1XxRS21z3NtcTz5JYGFjP0X/xbnC/0xLYm7s6Wj47djO2nVO
V+PIvsLP4fDl3ltORUxn4N50S0hOa+h5ev/o1dzoel9natvS2uReWm9+6mtrd37sYVNbW19l
XvPi1dru9Hvf29vQ0tPcfPPv0N3u6W53YVxcUFhaUFl3/v1cTEhFT2bXxsPM23Ntb27x5vpv
6d3X23pTUmfazc3T19rW721aV2hzY15PSk1UamVeX3zc0tz7Xl/z3trf1djU3PxqaO3r3Ot+
XVlUUVVYWVVWZO/Y2ehydvDa0s/O09rm6n7999za3eNwdVdOTk5l+t3tWEpGUVtWVF7Vx8HP
62JbXm197d7Z2d7sZV1eZuHPzcvX1+vt62dgVllpZ2tZUU9LXmnh3G1rXW/g7N5yeOfq3eZ6
6u/l3uPoentkZWlZXmFubVxYWfPPztPvXmzr1M/T2XVsY3fd2+JseG13d2ZpXVhgX2haVGxo
dF1PT1Lt2s7M2eb6++Pa3OFx6/PX1OtlU1Ru49bS2t7o9XH5cWdVTlRi/XRZVlZu3+DwYVlc
/uLX1973b/9+8el/3tvX2O5jV1pgZ2dvX15sbux6cnP95dDM09nza2V+49vg7H3v2uj/UUpN
Vuze2/9RSE1l4NnnaFldc/fe2tHS2vdcVV5/4tve6PF6aWhwf97Z19Pb2e50eGRwcmpqYWpj
V09LUVxu73v7+n758dzb1NLk3+rv9HB9Znl4fOrud2ZaXWZz6/jvcWBjaHvi8vtdcvva0NTZ
7G5kbOja1uXo8er8XVJRUGf5+HBbVFVr7OnzeW1+7tzc53hfY2j59fvd3tnrbnJ+1tDU3PX8
b3t4YV9fZXNodWBdYl/v+HxzcPvm39z29WRjbf31+XVhXnB+duf66eb07Ovf8vp3YGlrde7n
73Jv/fzo7/jz7vjm497g/GpZX2Tx19zsZ1JXZnnr/npydWtpYlxhanPt7/Lu7efr6fZp6+LY
0N7xZF9id+f+7WlyYWBmY2/0393f6fxseHfp6uz4bGd0ZHxibmn8cXd9a/Ry7PPr6u55/29s
cWltc+/j3996cWln+vDe2dzgfntcYW3t29xvfWJkZWFfWmRmZWhy+fj/cm7n7evq7dzl8urs
4ufocnF69+fn8H53c276fWpmXl5mdfr8b2pncXX9++zn+en06eP06Ply+nJ7e2xybHlycm5x
bWz8bHzu7OH273zr6d/u6vHy4eTk7nddbWDrfvzzX2VmXl1dYXfu7el/8m5oevj96nr54ufi
c2dhbObk3ez9bGlpaf5tdujo39/u73X7+vHs9Xh3cnj5ampnaWr1bOtyeXlx+nx49fv06nh8
bml3dnV9cnzvdu3s+drw5ODn6u/k+OJybGliemt6ZFhgXXp+eWhtauvr6OXs5Prrd3bu8eLt
5u5vcGB39fn0eXL+cv11b29reX32fHB2bX74/vz2/vfteP16fHr0cPhz8e7u9W9++3V082x1
cmv6fPF1c3R57+3sdHXs6uTn6/D86nv8dnL4/m5kZmBm/vV+8nNt8Xzm8Ob49+9v+nNo93d1
+XX5+nbq/Pn08+bv8n17/nNzc/hvdvhqcGxndW1pcW53cPLz7vHx+Ofs7ez5/Pj+/O/68v7x
eHpvcXPt/vR++2pwZGzx9u3sc3Rpcn396e7z8/7n9/V2bn1s7Hz78mVwZ2NtcfP88fp7+fd8
5Pzv7+/p/el07XdubP1/dPV593BubG56Z31sd3x+8Pt9cPlx8/7p8f7lferu5+Xp6fTq73ty
bGdua3F5a2pcaGFjeG5t+XPz+/P+8en14O/u+uXvcvZqb/n87+j562pt+nPpfOvt//dzfm91
+Pr4fG//dXx9e+xx9ftq9mRxbW9yfnt5enx9/fL96/3x9u74/e/t7+33c3lz/G1xZmh2fH3y
dvv2/Xx+9uzw8+vv5/zsdXv5e+37+nx3bGtua2tuc29/dnt48n/y8e3t7u7v/O/+/fdw+29u
cWx1a3L8b/D3d/Nz9H327evx6+r67/px9HJ/dntydml4bW38afJyb3h1dfr18+r99fF/63Pq
c/N8c/Xt+u/u9/Z89H37fHp3f3L8d/pv93l/+nx1/m//bX9vf/x6+Prv/fzxfu968nF9dXV0
b/5x62vueff7/PT07P738/n9evZz+21yem17bnj8ae9uffR69/Z8fu9o5Wvsd/b3dfFt7nB+
8f7s+Pv6/vz79O/w++5r+ndy93rtdvj9cfRt/HX8fP7tfPf8f3H6Z3BpbGprfXf6fvt373j1
6evw6v3ufO397vl9+Ht8cmxseXR1dnD0cv7+be1s7f1373bye/J6+XP1dnj0bO537fPw7vHp
+PPq+uv38/hwem17b3FpfmZsf2H8a259aPRq/vj77+zu+Oz+5vXx7/bu7+vs8v199Wz3Z/hx
d319d292bnFuc216dWn8bHv7evR77Xju8X937XXv6Pry8//59fT6/vf2be9ze/Rw+Xh2dnxt
a3f8//H2dvRp+HZy72rs9WfoZfvzbuZw7nx7+3ts8HD99Gzpb+t2+O509Hv5/nfwcP75ae97
d+9v83Jw9XN79HHq++739O948PF383n3fvx8c/ludW5vbHZtdW9/dP75/u3w7ur05vPt7Xrz
+XX1b/V6dnxofXBx+nv9d3tzbX9ofnJrfml7bHjwd+/v+en/8fTy7Pzs63T4bu4=

--bODY.pART.bOUNDARY.2
Content-Type: text/enriched
Content-Transfer-Encoding: quoted-printable

Listen to this sound the same way you viewed the GIF image: by clicking o=
n it or using the popup menu.


<Bigger><Bold>Including vs. Attaching</Bold></Bigger>


The above files are actually <Bold>included</Bold> as part=
 of this message.  You can also send pointers to files rather than the fi=
les themselves by using <Bold>attachments</Bold>.  This wi=
ll greatly reduce the size of your messages, but be aware that the recipi=
ent must have access to the original file in order to read it.  Here is a=
n attachment of the <Bold>/etc/passwd</Bold> file on your =
machine:=

--bODY.pART.bOUNDARY.2
Content-Type: message/external-body;
	access-type="local-file";
	name="/etc/passwd"

Content-Type: text/plain
Content-ID: <770050009.26123.3@halsoft.com>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948676130.21002.17@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--bODY.pART.bOUNDARY.2
Content-Type: text/enriched
Content-Transfer-Encoding: quoted-printable

Files can also be attached as <Italic>ftp</Italic> files o=
r <Italic>mail server</Italic> files.  In other words, the=
y don't have to be directly accessible to the recipient, but can be made =
available through ftp or a mail server.  Here is a file attached through =
ftp:=

--bODY.pART.bOUNDARY.2
Content-Type: message/external-body;
	access-type="anon-ftp";
	name="README.ftp";
	site="199.35.253.5";
	directory="halsoft/info";
	mode="ascii"

Content-Type: text/plain
Content-ID: <770050009.26123.4@halsoft.com>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948677500.21002.18@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--bODY.pART.bOUNDARY.2
Content-Type: text/enriched
Content-Transfer-Encoding: quoted-printable

If you have ftp (or anonymous ftp) access to the internet from your machi=
ne, click on this icon and ishmail will retrieve an informative message a=
bout using the <Bold><Bigger>H</Bigger></Bold>A<Bold><Bigger>L</Bigger></=
Bold> ftp site.


If you wish to modify the commands used to retrieve attachments, look in =
the file: <Bold>getmextern</Bold> in the <Italic>Is=
hmail</Italic> <Bold>bin</Bold> directory.


<Bigger><Bold>Other Types</Bold></Bigger>


Other types of files can be included or attached, like PostScript, JPEG i=
mages and MPEG videos.  Look at the <Bold>Include</Bold> a=
nd <Bold>Attach</Bold> functions under the <Bold>Me=
ssage</Bold> menu in the composition window to see what other typ=
es are supported.


Once again, thanks for trying <Italic>Ishmail</Italic>, an=
d don't hesitate to send us your comments or questions.


<Center><Bigger><Bigger>__ =
<Bold><Bigger>H</Bigger></Bold>A=
<Bold><Bigger>L</Bigger></Bold>  =
<Bold><Bigger>S</Bigger></Bold>=
oftware  =
<Bold><Bigger>S</Bigger></Bold>=
ystems __=
</Bigger></Bigger></Center>=


--bODY.pART.bOUNDARY.2--
