Return-Path: <>
Received: from navstar1.mcom.com ([205.217.251.46]) by hedgehog.mcom.com
          (Netscape Mail Server v1.1) with ESMTP id AAA29011
          for <atzet@netscape.com> Sun, 21 Jul 1996 16:59:17 -0700
To: atzet@netscape.com
From: mailusr1@navstar1.mcom.com
Reply-To: mailusr1@navstar1.mcom.com
Subject: Re: mailusr1@navstar1 3.0b6gold #1
Date: Sun, 21 Jul 1996 17:02:55 -0800
Message-ID: <19960722000255.AAA26598@navstar1.mcom.com>
MIME-Version: 1.0
Content-Type: multipart/mixed;;
                Boundary="===========================_ _= 1212158(26598)"
Content-Transfer-Encoding: 7bit
X-Mozilla-Status: 0011
Content-Length: 1213

--===========================_ _= 1212158(26598)
Content-Type: text/plain

default echo 1
default echo 2
default echo 3
default echo 4
default echo 5
--===========================_ _= 1212158(26598)
Content-Type: message/rfc822
Content-Disposition: attachment

Received: from hedgehog.mcom.com ([205.217.251.17]) by navstar1.mcom.com
          (Netscape Mail Server v2.0) with ESMTP id AAA3678
          for <mailusr1@navstar1.mcom.com> Sun, 21 Jul 1996 17:02:54 -0800
Received: from cabrillo.mcom.com ([207.1.136.82]) by hedgehog.mcom.com
          (Netscape Mail Server v1.1) with SMTP id AAA29001
          for <mailusr1@navstar1> Sun, 21 Jul 1996 16:59:09 -0700
Sender: atzet@netscape.com (Michael Atzet)
Message-ID: <31F2C3F2.D47@netscape.com>
Date: Sun, 21 Jul 1996 16:57:38 -0700
From: "Michael A. Atzet" <atzet@netscape.com>
X-Mailer: Mozilla 3.0b6Gold (X11; U; SunOS 5.5 sun4u)
MIME-Version: 1.0
To: mailusr1@navstar1
Subject: mailusr1@navstar1 3.0b6gold #1
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

mailusr1@navstar1 3.0b6gold #1
--
Michael A. Atzet                 atzet@netscape.com
Netscape Communications                415.919.3274
--===========================_ _= 1212158(26598)--
