Date: Fri, 29 Nov 91 07:13:35 EST
From: Nathaniel Borenstein <nsb@thumper.bellcore.com>
To: caseau@france.bellcore.com (Yves J Caseau)
Subject: Please check this out
Content-type: text/plain; charset=iso-8859-1
Content-transfer-encoding: quoted-printable
Message-Id: <635263359948238690.21002.3@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0

Please let me know if I've typed this correctly.
And thanks again for your help!  -- Nathaniel

Le courrier =E9lectronique =E0 la fran=E7aise n=E9cessite 
quelques caract=E8res sp=E9ciaux pour faciliter la t=E2che 
du lectein et =E9viter les ambigu=EFt=E9s