Path: flop.mcom.com!usenet
From: Jamie Zawinski <jwz@netscape.com>
Newsgroups: mcom.test
Subject: Re: attach this, spanky
Date: 26 Apr 1995 08:50:20 GMT
Organization: Netscape Communications Corporation, Mozilla Division
Lines: 103
Message-ID: <3nl1gc$lkb@flop.mcom.com>
References: <3na39m$3lf@flop.mcom.com>  <3nkvv6$kmf@flop.mcom.com>  <3nl02e$kmf@flop.mcom.com>  <3nl0gd$l55@flop.mcom.com>
NNTP-Posting-Host: lr1-port2.mcom.com
Mime-Version: 1.0
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
X-Mailer: Mozilla 1.1 (X11; U; Linux 1.1.47 i586)
X-URL: news:3nl0gd$l55@flop.mcom.com

Path: flop.mcom.com!usenet
From: Jamie Zawinski <jwz@netscape.com>
Newsgroups: mcom.test
Subject: Re: attach this, spanky
Date: 26 Apr 1995 08:33:17 GMT
Organization: Netscape Communications Corporation, Mozilla Division
Lines: 86
Message-ID: <3nl0gd$l55@flop.mcom.com>
References: <3na39m$3lf@flop.mcom.com>  <3nkvv6$kmf@flop.mcom.com>  <3nl02e$kmf@flop.mcom.com>
NNTP-Posting-Host: lr1-port2.mcom.com
Mime-Version: 1.0
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
X-Mailer: Mozilla 1.1 (X11; U; Linux 1.1.47 i586)
X-URL: news:3nl02e$kmf@flop.mcom.com

Path: flop.mcom.com!usenet
From: Jamie Zawinski <jwz@netscape.com>
Newsgroups: mcom.test
Subject: Re: attach this, spanky
Date: 26 Apr 1995 08:25:50 GMT
Organization: Netscape Communications Corporation, Mozilla Division
Lines: 69
Message-ID: <3nl02e$kmf@flop.mcom.com>
References: <3na39m$3lf@flop.mcom.com>  <3nkvv6$kmf@flop.mcom.com>
NNTP-Posting-Host: lr1-port2.mcom.com
Mime-Version: 1.0
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
X-Mailer: Mozilla 1.1 (X11; U; Linux 1.1.47 i586)
X-URL: news:3nkvv6$kmf@flop.mcom.com

Path: flop.mcom.com!usenet
From: Jamie Zawinski <jwz@netscape.com>
Newsgroups: mcom.test
Subject: attach this, spanky
Date: 26 Apr 1995 08:24:06 GMT
Organization: Netscape Communications Corporation, Mozilla Division
Lines: 52
Message-ID: <3nkvv6$kmf@flop.mcom.com>
References: <3na39m$3lf@flop.mcom.com>
NNTP-Posting-Host: lr1-port2.mcom.com
Mime-Version: 1.0
Content-Type: multipart/mixed;
	boundary="---------------------------2082357617733318156662372089"
X-Mailer: Mozilla 1.1 (X11; U; Linux 1.1.47 i586)
X-URL: news:3na39m$3lf@flop.mcom.com

This is a multi-part message in MIME format.

-----------------------------2082357617733318156662372089
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=us-ascii

Here comes an attachment of type message/rfc822:

-----------------------------2082357617733318156662372089
Content-Transfer-Encoding: 7bit
Content-Type: message/rfc822

Path: flop.mcom.com!usenet
From: Sharon Iimura <sharoni>
Newsgroups: mcom.test
Subject: Test for Bug 4498
Date: 22 Apr 1995 05:13:26 GMT
Organization: Netscape Communications Corporations
Lines: 22
Message-ID: <3na39m$3lf@flop.mcom.com>
NNTP-Posting-Host: diva.mcom.com
Mime-Version: 1.0
Content-Type: multipart/mixed;
	boundary="-------------------------------12402385823900"
X-Mailer: Mozilla 1.1 (X11; U; SunOS 5.4 sun4m)
To: sharoni
X-URL: http://home.netscape.com/eng/mozilla/1.1/unix-1.1.html

This is a multi-part message in MIME format.

---------------------------------12402385823900
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=us-ascii

http://islay.mcom.com:8008/regression/test1.1b3/bug4498/

-- 
     Sharon Iimura
     Netscape Communications Corporation

---------------------------------12402385823900
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

<BASE HREF=3D"http://home.netscape.com/eng/mozilla/1.1/unix-1.1.html">

<TITLE>Not Found</TITLE><H1>Not Found</H1> The requested object does not ex=
ist on this server. The link you followed is either outdated, inaccurate, o=
r the server has been instructed not to let you have it. 
---------------------------------12402385823900--

-----------------------------2082357617733318156662372089--


