Path: flop.mcom.com!news-mail-gateway
From: MAILER-DAEMON@netscape.com (Mail Delivery Subsystem)
Newsgroups: mcom.incoming.client
Subject: Returned mail: Host unknown (Name server: maine.link.net: host not found)
Date: 26 Apr 1995 17:08:35 -0700
Organization: Local Mail/News Gateway
Lines: 109
Sender: daemon@flop.mcom.com
Approved: usenet@netscape.com
Message-ID: <199504270008.RAA17252@neon.netscape.com>
NNTP-Posting-Host: flop.mcom.com
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="RAA17252.798941312/neon.netscape.com"

This is a MIME-encapsulated message

--RAA17252.798941312/neon.netscape.com

The original message was received at Wed, 26 Apr 1995 17:08:30 -0700
from cronos.mcom.com [198.93.94.116]

   ----- The following addresses had delivery problems -----
<drwebb@maine.link.net>  (unrecoverable error)

   ----- Transcript of session follows -----
550 <drwebb@maine.link.net>... Host unknown (Name server: maine.link.net: host not found)

   ----- Original message follows -----

--RAA17252.798941312/neon.netscape.com
Content-Type: message/rfc822

Return-Path: client@netscape.com
Received: from cronos.mcom.com (cronos.mcom.com [198.93.94.116]) by neon.netscape.com (950215.SGI.8.6.10/8.6.9) with SMTP id RAA17240 for <drwebb@maine.link.net>; Wed, 26 Apr 1995 17:08:30 -0700
Message-Id: <199504270008.RAA17240@neon.netscape.com>
Date: Thu, 27 Apr 95 01:14:08 0800
From: Christopher Lamey <client@netscape.com>
Organization: Netscape Communications
X-Mailer: Mozilla 1.1N (Macintosh; I; 68K)
MIME-Version: 1.0
Newsgroups: mcom.incoming.client
To: drwebb@maine.link.net
Subject: Re: 90 Day product Support
References: <199504251257.IAA09959@maine.mainelink.net> <server-2504951544190001@ub.mcom.com>
X-URL: news:server-2504951544190001@ub.mcom.com
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=us-ascii

>drwebb@mainelink.net (dennis r. webb) wrote:
>> 1) VIEWING EXTERNAL IMAGES
>>         I have LView 3.1 and have told Netscape in the Setup that I do. I have
>>         not yet been able to get my Image Radio Button to Light up, it remains
>>         grayed out at all times.
The Image button on the main interface, between Reload and Open, is for reloading images 
on the page you're viewing.  Sometimes Netscape Navigator incorrectly loads a file's 
images.  The Image button is for rectifying this problem.  Netscape Navigator has built in 
capabilities for viewing jpeg and gif files.  You don't need to configure a viewer for this.  

>> 
>> 2) HELPER APPLICATIONS
>>         MPEG : Downloaded MPEGWIN.ZIP, MPEGXING.ZIP. Was not sure if I should
>>                download MPEGW32g.ZIP. I have a Pentium 90 Hz system with 16
>>                Megs of RAM, 4 Meg Video Vram PCI CARD and run windows in
>32 Bit
>>                Disk access and 32 Bit File access. My conventional memory is
>>                617 K .
>>                Noted that you have "Netscape Navigator Sound Installation 
>>                Tutorial for Windows". This explains how to Install "WHAM 1.31
>>                Audio Player". Which MPEG should I install and how to I
>associate
>>                it with NETSCAPE ?
There are hundreds of mpeg players on the Internet.   Which one you want is a matter of preference.  We have WHAM 1.31 on our page b=
ecause it's a widely used and accepted player.   For more players and info go to this URL:

http://www2.netscape.com/assist/helper_apps/index.html

No matter what player you choose, configuring them in Netscape Navigator is the same.  In the Options:Preferences:Helper Apps menu, =
you can tell Netscape Navigator what to do with certain files it downloads.   To play MGPEGs, set it like this:
MIME Type: video/mpeg
Application: Wham 1.31 (You can browse to make sure the path is right)
Action: Launch
Extension: mpeg, mpg, mpe

>>         TELNET : Downloaded WINTELB3.ZIP and TRMPTEL.ZIP. Which should I
>use and
>>                  also How do I associate it with NETSCAPE ?
>>                  
Once again, which one you use is a matter of personal preference.  Both are well known and used applications on the Internet.  To ha=
ve Netscape Navigator use one of them, go to the Options:Preferences:Applications and Directories menu.  There you can set Netscape =
Navigator to use a Telnet application.  Simply use the browse option to specify the one you want to use.

>> 3) QUICKTIME
>>                 Noted that when I was in NEWSGROUPS that I need QUICKTIME for
>>                 some Videos. Was planning on downloading it from
>gatekeeper.dec.
>>                 com?pub/msdos/win3/desktop. There is a note in the File Index
>>                 that says "(REMOVED by wayneb@apple.com). Do you know of
>another
>>                 location to find QUICKTIME (qtw111.zip) and also how do
>I assoc-
>>                 iate it with NETSCAPE ?
Try

ftp://ftp.cica.indiana.edu 

If it's not there, do a search for the word Quicktime.  The configuration the same as for  a MPEG player.  

MIME Type: video/quicktime
Application: MoviePlayer (You can browse to make sure the path is right)
Action: Launch
Extension: qt

Thank you for using Netscape!
--
Chris P. Lamey
Netscape Customer Support
client@netscape.com




--RAA17252.798941312/neon.netscape.com--
