X-Andrew-Authenticated-As: 4099;greenbush.galaxy;Nathaniel Borenstein
Received: from Messages.8.5.N.CUILIB.3.45.SNAP.NOT.LINKED.greenbush.galaxy.sun4.41
          via MS.5.6.greenbush.galaxy.sun4_41;
          Fri, 12 Jun 1992 13:29:05 -0400 (EDT)
Message-ID: <UeCBvVq0M2Yt4oUA83@thumper.bellcore.com>
Date: Fri, 12 Jun 1992 13:29:05 -0400 (EDT)
From: Nathaniel Borenstein <nsb>
X-Andrew-Message-Size: 152+1
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="Interpart.Boundary.IeCBvV20M2YtEoUA0A"
To: Ned Freed <ned@innosoft.com>,
    ysato@etl.go.jp (Yutaka Sato =?ISO-2022-JP?B?GyRAOjRGI0stGyhK?= )
Subject: MIME & int'l mail

> THIS IS A MESSAGE IN 'MIME' FORMAT.  Your mail reader does not support MIME.
> Please read the first section, which is plain text, and ignore the rest.

--Interpart.Boundary.IeCBvV20M2YtEoUA0A
Content-type: text/plain; charset=US-ASCII

In honor of the Communications Week error about MIME's ability to handle
international character sets. a screen dump:

[An Andrew ToolKit view (mailobjv) was included here, but could not be
displayed.]
Just for fun....  -- Nathaniel

--Interpart.Boundary.IeCBvV20M2YtEoUA0A
Content-Type: multipart/mixed; 
	boundary="Alternative.Boundary.IeCBvV20M2Yt4oU=wd"

--Alternative.Boundary.IeCBvV20M2Yt4oU=wd
Content-type: text/richtext; charset=US-ASCII
Content-Transfer-Encoding: quoted-printable

In honor of the <italic>Communications Week</italic> error about MIME's abilit=
y to handle international character sets. a screen dump:<nl>
<nl>

--Alternative.Boundary.IeCBvV20M2Yt4oU=wd
Content-type: image/gif
Content-Description: Some international characters
Content-Transfer-Encoding: base64

R0lGODdhEgLiAKEAAAAAAP///wAA////4CwAAAAAEgLiAAAC/oSPqcvtD6OctNqLs968
+w+G4kiW5omm6sq27gvHX0DX9o3n+s73/g8MCofEovGITCqXzKbzCY1CEdKq9YrNarfc
rvcLllLDQUDAjD6r0+y1uw1/y+P0ub2Ov+vz/L2/D/gnGEg4aFiIeKiYyLiodjR25kDW
WOloiXmpmcm56dkJ+ikaSqqn81ATaXbKmlX6OhoLOytbS3trm4sbmLP6uOqrKmmT1ovj
27Sru6zczPzsHA09ndj6SxN8kIoNjG29PUUtLk0+bl6Ofq7eZux9zW0APtzdDqwN7x0/
z5Pev/7vLyDAgQKL9RpDT5K+RwzdHWuILNgwOzsKErxoMSPG/o0aqz28kVDYGokHQRKj
gkwOq44cW7J86TJmuW/usi2kpy/ltojETPY0aAymUJlEhxotquigAofCIgLtybCbxJTs
giI9ivWq1qwwaUJVSLLdx6g2HTLltzUtV7Vs184cO1bVpDBu29qti/euqFNzwZIpozev
4MCEB8eBdO+v4sWMGzt+DDmy5IqJJ1u+jDmz5s2ct8j4DDq06NGkS5s+jTq16tWsW7t+
DfvCgNm0a9u+jTu37t28e/v+DTy48OHEixs/jjy58uXMmzt/Dv05gujUq1u/jj279u3c
u3v/Hn06+PHky5s/jz69+vXSD7B/Dz++/Pn068cXbz+//v38/vv7r4/ffwIOSGCBBh7Y
W4AILshggw4+CJ6CEE5IYYUWXphbgAJsuCF0AtD2YW8hNtdhbhyOaB+Kuqk4AIcmcsfi
bSXONmN5MeJ2I305brfjcj0up6F1Jd6I4o848rZjiEYS9+OStS2p4ohKPgmjb1Gm1+R/
Tla3pXFdEhdkcjkO+SKIHu425ZnOOXkljW6ayaOVtn0pJJJamkfncHkGF6aZM7rY4odS
1kiloDQOCaigg075Z5E1JvlmooGCSGajSgIa6KB+jlnoooeSOemJboLaYqifeloqoZRa
SmWrn646Kqo4smqqqzLKd6KmmXZoKJSXqjrrqYaGKiqlwe35/puGiTLqZ6pwHjksnI6+
uSm1Uj6bJKmKjlqts5G6eu2h1No6qbfm9lpquuKe62y07pYb47Xhqmtts7FyOy626qLb
5q24jssiv8D1a+ec7X5LbsHU9ZmvvOaiuW6xRUrr4ryL/gkxu1GKGu6jTxa777MG61tu
yOjS6zC3J6fKscKKYtpvzPTuGu/IB09cZnxp5nvzwDYr3OywO/Oc8cLuiTyzw9FmzKu0
4JpM8sxEO50y0vOGjHS9U2ONcr3bAmxvz1Vv7fWRTz9NsNn6rtwjstgN3WbFPif8285p
s3kdw0kHzbW/7Kb7btUWR2124DYbjvC7WkvdquBQj4x4071K/orv4WFfzTXiUQ+uNOAi
/ts1ycDmTPaKhBOKt3V6B6ztq2r/qmvHckdKa6YmwkwqrFhjWjLudtspO+yrxk6xxjLm
7jrIvutue/LHy7r845/DB3Lf1U+fq3COVuw7lNhJKCaG4hd9rHpuj68n+reBr377ProP
/9zwsx9//edhbrnp59vPv3D09w/AKvEsVwS0FAEDiMD2GCCBDOwO/s4GOc81cILG+R8F
L4iclx2weSsT1vUwCELdKIt38qPTl0ionP3Nik0qlJMLs4Mzg8mKaltrYQgtJKE9PZBx
WXMZ6eSXPtNNLWDP4RTQruOxW2mQdwUcXelu2L8cHlGGQvzh/vTIV7fjQGqIfoPhFKmz
tHhhbH82hCKEpMg8FNpLXtGz2+hYJzzXqW13tFIeqBAVR7JF73an+pkf3za8MTZxiU2s
ohkZiMbM+RBhSmQckVQFtx7KDHORVNnfiJgzxZWJklZEotMKZck5bRCLhwxgInf4uk8O
r2R9ZBrlFvcz2X0sd51b4gCrqMnCicyIceqb7SR3tyuWEoGn7GEmVQm1wUGsYxD026Ua
h0ylDe2Wx0SlBH3ZRUDG8F4cnOUH/zjMKB4Ngtak47dS9jtn7q5yWzSV4zw3tnX6cnua
xKTyhPm2YG5raYTrZDjtl8jmCXSOTVvXruj4RgMaS46GBJxC/g3aPYbWDoW/0l2a0tbQ
OtFMUjiD3SDn+E8AWhCkDypnL7EpuifiCXi6CqlL1zdOBKrxfk48njFfitMFjTSnPO2p
T2uz058KdajhDCpRj4rUCxo1qUxtKv8UNNMyWqmmuLIhVZ2KVQL1qWYkzSg+wanFbAbR
S2DNqlkHpDexjvWmelxTEd161rgaaHWbehT08DhDdeLVovDq3V4N2s3a8bBWAkWdXA+L
1ph2k53QZKzU2rbQSrKMm3FTJ2XzB629NQyxnO0P+zTX0ZaVFZfRFK3oXrk5hKLyZPek
W2dfC5/PSq+jfzxhSq1mOWZiFrQ3FRgsBwvb4KJnqw61XtkS/sdWRcIzbMeVoDKN91tQ
1nO0wq3ueKDaKJbdMY12Zd7zFlfH/NmRu+mU2BsphkfvWne95Fmqv5AlVfbKd6jutel8
74vf4tQ3v/ztL5gU698ACxg5+x2wgQ9c4AMr2L8JXrCD79vgB0vYuhGesIVfW+ELa1iu
Gd6wh7Ha4Q+LGKkhHrGJf1riE6sYpylesYuLCuAXy9ipLZ6xjTFY4xvrGJEx3rGPc5rj
Hws5fkEespHRV+QjKxmHPV6ykymY5CdLWadNnrKVn1rlK2vZfVHespf10+Uvi3k+YR6z
mdlT5jOr+TxpXrObI5TlN8v5P7Jta1vjO+c826bOjx1k97Kn/udAN4fP7eSq0ASNaOWA
j5DLYtbGCpjoSFcwxtu8HCTxhWdJnzmHlVbZKDc6U02LGjdQDZ0o4znqVE96gc4EtHYh
7edQq1rUi0amtzrowTFx7Juz3jSlf8u9yZIr073Wcq0r/TXUQrrYzB7AovXpzlQ2m9m1
BjWzPhnrq047z9XWX0u3DW6Ysjrc5IZOm8ut6nOje9TqXrem2+3uSMM73oieN70Dbe97
czvO+u43bfLtbzcDPOBqHjjBzWzwg4s54Qr3MsMbbmx+Q3zdD5/4lCtu8SdjPONL3jjH
j0xcYr+woibjNZO8V5xnWkjbA9teuUNOnueiOoWuVekxy+fV/rBS96va2y25YT4eXlls
n2+tOXAX+T4SFZ05z902zAV7ar7Sjkh/6xmSwpvQ82L9Yrt0oiBbGVhGoWq8fBWsrveV
XbqJfMtBmpxjMcvYB7KNb7zmJPLYirxkKxel1roo2sS+2ceubZqrfdg81UrtmPq26qL0
pjlvrkjInjqXRg8eb/seamXSk5+Wp+Zswc4pocHMj2t3uOIP9nZdYrrT4F3bEd+J+OZe
nu8+N3XgL2lZ6NJ+8Zw0eq+VRVjKy15cwt/7zNF2uU2m0nEy7+1tNTf8a3Iu+TVE/eHv
DXSH6prrjTvv1L1Wd4WulupTV5x58zpL8I5dvLgjr9bOf3P4/ksU3Wk26ceN3GZZ31/J
Ht//j/vvfzsGgAF4YwNIgDNmgAf4YgmogCvGgA14Yg8IgSMmgRP4YRVogRuGgRl4YRvI
gRPmgR/4YCEoggtGgiWIYBKHgvimgiu4b+Pmgql2gjHIYC0IbqXHc1I2gyqGg1+kgza4
bT1IShcHhJHmani1eFcHdmjiUcXlaqzkgEVoZdnzhKp3S7iGRSgnXc61cxoohYkmWXQH
REeXNb5FeAj4hYgWhtpHhrjFJMDWhRq2gxIWhrKURb4HedOCh14Ig+FWPVdjcoUTiAS1
aw+1gGlocUL4f4g4cYroY3NIHwtAg+oDiWS2Z5OIZIwYQpKI/oniU4nywYmdeCFF1iVu
YyQY1VjJEYqiWCGk2HM6x4SglFkqtIqsOCGuiHNktUz9xFwEpgC2yGR9yFF3BXgHhVDc
pERjJ2tNF3vDUYvA6CAhd20aM428dXd9BXu5x0uK9ovQeIunVznCQjOfZ4coVY6FF102
BxzP6I1UBoPxFExxt0vpCIjp2HqZBSTd2I7RqFimNXzMR3zUl1sC2UX8xDfcmAD7+CCy
BUdS92rGQnJyh15L6E3o2ELsqJAFQlw8hZEZmVjCyHJQ1JEeSWeaSJKPaJInqWOfqJJZ
xZItSWMpCZMy9pIzmVQ1aZNHhZM5SV8yyZMR6JM/SYFBKZQXgEiURcmHAICUV7aTS8li
R+mUIAiVUTmCU0mVJmiVV5mCfaiVQtaUXVlKXwmWZiSWY3lDZWmWIISWaalUWcmW+bWW
b9lAcSmXCUSXdWlKbomX7HWXe4llXOmXQAmYgTmUg0mYRmmYh5mUscGYjemYjwmZkSmZ
k0mZlWmZl4mZqVEAADs=

--Alternative.Boundary.IeCBvV20M2Yt4oU=wd
Content-type: text/richtext; charset=US-ASCII
Content-Transfer-Encoding: quoted-printable

<nl>
<nl>
Just for fun....  -- Nathaniel<nl>

--Alternative.Boundary.IeCBvV20M2Yt4oU=wd--

--Interpart.Boundary.IeCBvV20M2YtEoUA0A--
