Message-ID: <31C105ED.41C62@netscape.com>
Date: Thu, 13 Jun 1996 23:25:49 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: attached image cache test (test 2: inline disposition)
Content-Type: multipart/mixed; boundary="------------167E2781446B"
X-Mozilla-Status: 0001
Content-Length: 3748

This is a multi-part message in MIME format.

--------------167E2781446B
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Content-Description: a message with a text/plain body

Message-ID: <31C10324.41C62@netscape.com>
Date: Thu, 13 Jun 1996 23:13:56 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: test message one (a message with a text/plain body)
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

This is the first attached message.


--------------167E2781446B
Content-Type: image/gif; name="one.gif"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="one.gif"

R0lGODdhpAAoAPAAAP///wAAACwAAAAApAAoAAAC/oSPqcvtD6OctNqLs968+w+G4kiW5omm
6sq27gvH8kzX9o3nuhP0frCT/HpBkK8I+RmUyM2xyXgipFALtbq8AphYirb63RK73nF2zOUe
hgt2W52Ar6VMuTgsux7ZQ7P4HEfkdgf4BtRAtTdIyHijRwd52Bg5J/lXqIDXeCeZ2OlX82jp
+VlaeYq5iRrlR7qqOiM61do6a4rpmgkaOEp7m0oj+/o1SHnWZ/mq28tciYwjnJo73Rxhx2mb
DawTvWmsugiLuAucKw4Naj5ppm6bPL4LZ35t0z2P9m3YyRPfX328Joc9X876HFv07EEdYgQL
kouR0I3ENOxKJXQ2waC+M0Ph6JFxguzdx5EVHpE8eaEfypUZkz1kCZOXx5g0a9q8iTOnzp08
e/r8CTSo0KFEix4oAAA7
--------------167E2781446B
Content-Type: image/gif; name="two.gif"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="two.gif"

R0lGODdhmgAwAPAAAP///wAAACwAAAAAmgAwAAAC/oSPqcvtD6OctNqLs968+w+G4kiW5omm
6sq27gvH8kzX9o3n+s73/g8MCoeBojFAPCqVQ4axCXgapNEiVEEVWg/Z7ZXr1Say0S+CDESe
w2XzNHx8e+Njeh0tZzfwy+rTnqfWQvYXtyRYJXfnN7eFh6WXByYIVxhpQkhlp9lI2bk2GfHo
F/q25omYkonY9an4Sgob6zDKSXm6uLKKWzrFO2v7u3cJ7MjKNjqy2zt76lp8mLqQLGV4nJos
sizbqtZtyjxBbYX0lxt+st0cLMuITUwLz8R43p6OXHnd+z2d3S99x5u6ZijU8Yu1SZ4mUfCg
/UN3752+fdEEHnLmzx4kRlCQyGX0cNFdoJGwOoWcBDDgvH4c/zV0gxEQTJiZZtpMVOfmTHw6
bZ7sCTSo0KFEixo9ijSp0qVMmzp9CjWq1KlUq1qNUAAAOw==
--------------167E2781446B
Content-Type: image/gif; name="three.gif"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="three.gif"

R0lGODdhqAAzAPAAAP///wAAACwAAAAAqAAzAAAC/oSPqcvtD6OctNqLs968+w+G4kiW5omm
6sq27gvH8kzX9o3n+s73/g8MCofEovGIrASWzMCwCY0CoEkHs3g1ZKfLw7aq+Aa7XrLWeUaD
w2ahOp1Qi9dw4pt7l7fp9TS6WbaHJzh4F0i4MBfohwAI2PgIqUgidkUV9UZW2UVVNxmHWNjJ
iOdplvUZsnm61cqqBwu5CPEZ+YWKO8ule7Iq+dvnGttX+lDbdstKbIkcCuLLewtcTJ1syHa9
3HxtTe1dAq3Nbft6KGUc2s1rfonp/BHurT6f+c5wXJ+fiJhqEq9ebc8oYhPwTftGcN2Kf9t0
AQRlD1uDh4oiScrWS2BDZoeahFlpFcFgNH4gSU1RwVCfn3Pu8ln8iJEiyYGYUtQstDJnMFg3
D9FyB7Ejrpc+sWFc05KP0okalzoFxeap1F2ypkrtaTWr1q1cu3r9Cjas2LFky5o9izat2rVs
27p9Czeu3K4FAAA7
--------------167E2781446B
Content-Type: image/gif; name="four.gif"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="four.gif"

R0lGODdhmgA5APAAAP///wAAACwAAAAAmgA5AAAC/oSPqcvtD6OctNqLs968+w+G4kiW5omm
6sq27gvH8kzX9o3n+s73/g8MCofEovGITAIDzGZg6IxGlYbm0ZrAKrVE7oFJBXiF42q4vAQj
nuKzuop1fsdTRd0ub3jZ+L02L2YFOOL3NCXFFwiXGGgIGPfWt8bY6BjJhQlJ+VHI9/j2Byqa
OKpXmnW6OEmqNhhSuBqrOts453kZuSqFyhjK+jtnAmsra0ZM61vMe8yMjAusMkxb25fqi8iQ
uVycCZ0iTT2tKfs8sbfN3K18Aq7u3OuKtnC+ntwsL9Je/r5uuzmfSxK3fdPY5XLHr1Kzal9M
/RvobRC+VwcJhkOkaZc/UXwTFUo8ZM9gnZF57oTaeGfRQ4wPUvp719EIxodhoFSsSSVgQJxd
4PHMqfGn0KFEixo9ijSp0qVMmzp9CjWq1KlUq1q9ijWr1q1cu3r9CtZpAQA7
--------------167E2781446B
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Content-Description: a message with a text/plain body

Message-ID: <31C10333.167E2@netscape.com>
Date: Thu, 13 Jun 1996 23:14:11 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: test message two (a message with a text/plain body)
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

This is the second attached message.

--------------167E2781446B
Content-Type: message/rfc822
Content-Disposition: inline
Content-Description: a message which contains a message
	(which contains a message, which has a text/plain body)

Message-ID: <31C106F6.59E22@netscape.com>
Date: Thu, 13 Jun 1996 23:30:14 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: a message which contains a message
	(which contains a message, which has a text/plain body)
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Content-Description: a message which contains a message
	(which has a text/plain body)

Message-ID: <31C106E3.15FB2@netscape.com>
Date: Thu, 13 Jun 1996 23:29:55 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: a message which contains a message
	(which has a text/plain body)
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
Content-Description: a message with a text/plain body

Message-ID: <31C106D2.794B2@netscape.com>
Date: Thu, 13 Jun 1996 23:29:38 -0700
From: Jamie Zawinski <jwz@netscape.com>
Organization: Netscape Communications Corporation, Mozilla Division
X-Mailer: Mozilla 3.0b5 (X11; U; IRIX 5.3 IP22)
MIME-Version: 1.0
To: Jamie Zawinski <jwz@netscape.com>
Subject: a message with a text/plain body
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Foo!

--------------167E2781446B
Content-Type: text/html
Content-Disposition: inline

And this is some <B><FONT COLOR=red>HTML</FONT></B>

--------------167E2781446B--
