Path: flop.mcom.com!news.Stanford.EDU!agate!tcsi.tcs.com!uunet!vixen.cso.uiuc.edu!gateway
From: Internet-Drafts@CNRI.Reston.VA.US
Newsgroups: info.ietf
Subject: I-D ACTION:draft-smith-ipatm-bcast-00.txt
Date: 25 Apr 95 15:09:13 GMT
Organization: University of Illinois at Urbana
Lines: 96
Approved: Usenet@ux1.cso.uiuc.edu
Message-ID: <9504251109.aa04587@IETF.CNRI.Reston.VA.US>
Reply-To: Internet-Drafts@CNRI.Reston.VA.US
NNTP-Posting-Host: ux1.cso.uiuc.edu
Mime-Version: 1.0
Content-Type: Multipart/Mixed; Boundary="NextPart"
Originator: daemon@ux1.cso.uiuc.edu

--NextPart

here are a couple of external bodies:

--NextPart
Content-Type: Multipart/MIXED; Boundary="OtherAccess"

--OtherAccess
Content-Type:  Message/External-body;
        access-type="mail-server";
        server="mailserv@ds.internic.net"

Content-Type: text/plain
Content-ID: <19950424144009.I-D@CNRI.Reston.VA.US>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948541830.21002.5@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0

ENCODING mime
FILE /internet-drafts/draft-smith-ipatm-bcast-00.txt

--OtherAccess
Content-Type:   Message/External-body;
        name="draft-smith-ipatm-bcast-00.txt";
        site="ds.internic.net";
        access-type="anon-ftp";
        directory="internet-drafts"

Content-Type: text/plain
Content-ID: <19950424144009.I-D@CNRI.Reston.VA.US>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948543400.21002.6@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--OtherAccess
Content-Type: message/external-body;
        access-type="URL";
        url="http://home.netscape.com/
		people/
		jwz/
		index.html"

Content-Type: TEXT/HTML
Content-ID: <spankulate@hubba.hubba.hubba>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948549480.21002.7@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--OtherAccess
Content-Type: message/external-body;
        access-type="local-file";
        name="/some/directory/loser.gif"

Content-Type: image/gif
Content-ID: <spankulate3@hubba.hubba.hubba>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948550940.21002.8@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--OtherAccess
Content-Type: message/external-body;
        access-type="afs";
        name="/afs/directory/loser.gif"

Content-Type: image/gif
Content-ID: <spankulate4@hubba.hubba.hubba>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948552090.21002.9@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--OtherAccess--

--NextPart--
