Return-Path: <bob@sarad.cs.su.oz.au>
Received: from thumper.bellcore.com by greenbush.bellcore.com (4.1/4.7)
	id <AA24448> for nsb; Sat, 18 Jan 92 01:20:08 EST
Received: from joyce.cs.su.oz.au by thumper.bellcore.com (4.1/4.7)
	id <AA17087> for nsb@greenbush; Sat, 18 Jan 92 01:20:04 EST
Message-Id: <9201180620.AA17087@thumper.bellcore.com>
Date: 18 Jan 1992 17:19 (Saturday)
From: bob@cs.su.oz.au (Bob Kummerfeld)
To: nsb@thumper.bellcore.com
Subject: another Hebrew test
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="partsep28042"


--partsep28042
Content-type:  text/plain

The next part of the message is the last few verses of Bereshit.

Bob


--partsep28042
Content-type:  text/plain; charset=iso-8859-8
Content-Transfer-Encoding: base64

4fjg5SDt6fD5IPLh+SDl6ennIOnw+SDh9/LpIOnu6SDp5OnlIOTw+SDk+PnyIPLh+SDt6fj2
7iD1+ODhIOH38ukg6efp5SAyOCA0NyAxCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgOuTw+SD64O7lIO3p8gog6unw
6fLhIO/nIOn64PbuIODwIO3gIOXsIPju4OnlIPPx5ensIOXw4ewg4Pj36eUg+uXu7CDs4Pj5
6SDp7ukg5eH49+nlIDI5IDQ3IDEKICAgICAgICAgICAgICAgICAgOu3p+Pbu4SDp8Pjh9/og
4PAg7OAg+u7g5SDj8ecg6ePu8iD66fny5SDp6/jpIPrn+iDq4+kg4PAg7en5CiAgIDrq+OHj
6yDk+fLgIOnr8OAg+O7g6eUg7fr44ffhIOnw+vjh9+Ug7en49u7uIOnw+uD58OUg6frh4CDt
8iDp+uHr+eUgMzAgNDcgMQogICAgICAgICAgICAgICAgICAgUCA65Oju5CD54Pgg7PIg7OD4
+ekg5ef6+enlIOXsIPLh+enlIOnsIOTy4fnkIPju4OnlIDMxIDQ3IDEK

--partsep28042--

