Path: flop.mcom.com!news.Stanford.EDU!bloom-beacon.mit.edu!hookup!paladin.american.edu!auvm!GAROPA.NPT.NUWC.NAVY.MIL!gary
Comments: Gated by NETNEWS@AUVM.AMERICAN.EDU
Newsgroups: rec.arts.bonsai
X-Hpvue$Revision: 1.8 $
Mime-Version: 1.0
Content-Type: Message/rfc822
X-Vue-Mime-Level: 4
Mailer: Elm [revision: 70.85]
Message-ID: <BONSAI%95042607552288@CMS.CC.WAYNE.EDU>
Date: Wed, 26 Apr 1995 07:50:09 EDT
Sender: Internet Bonsai Club <BONSAI@CMS.CC.WAYNE.EDU>
From: Gary Bolstridge <gary@GAROPA.NPT.NUWC.NAVY.MIL>
Subject: Re: Newsletters & Shows
Lines: 16

content-type:text/plain;charset=us-ascii
mime-version:1.0
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948401430.21002.4@Jeffreys-MacBook-Air.local>

I have been reading the archived discussions and saw a lot of activity
around Dec 1994 about starting a newsletter, posting area and club shows,
even a judged show of trees!

Has there been any progress on any of these subjects?

With all the current traffic of people traveling and requesting information
for certain dates, there is an obvious need for posting club shows. The FAQs
might need updating to list area vendors.

Also, has there been any progress on the listings of clubs?

Gary Bolstridge
Newport (RI) Bonsai Club