Path: flop.mcom.com!news.Stanford.EDU!agate!tcsi.tcs.com!uunet!vixen.cso.uiuc.edu!gateway
From: Internet-Drafts@CNRI.Reston.VA.US
Newsgroups: info.ietf
Subject: I-D ACTION:draft-smith-ipatm-bcast-00.txt
Date: 25 Apr 95 15:09:13 GMT
Organization: University of Illinois at Urbana
Lines: 96
Approved: Usenet@ux1.cso.uiuc.edu
Message-ID: <9504251109.aa04587@IETF.CNRI.Reston.VA.US>
Reply-To: Internet-Drafts@CNRI.Reston.VA.US
NNTP-Posting-Host: ux1.cso.uiuc.edu
Mime-Version: 1.0
Content-Type: Multipart/Mixed; Boundary="NextPart"
Originator: daemon@ux1.cso.uiuc.edu

--NextPart

A New Internet-Draft is available from the on-line Internet-Drafts 
directories.                                                               

       Title     : IP Broadcast over ATM Networks.                         
       Author(s) : T. Smith, G. Armitage
       Filename  : draft-smith-ipatm-bcast-00.txt
       Pages     : 7
       Date      : 04/24/1995

This memo describes how the IP multicast service being developed by the IP 
over ATM working group may be used to support IP broadcast transmission. 
The solution revolves around treating the broadcast problem as a special 
case of multicast, where every host in the subnet or cluster is a member of
the group.                                                              

An understanding of the services provided by draft-ietf-ipatm-ipmc-04.txt 
is assumed.                                                                   

Internet-Drafts are available by anonymous FTP.  Login with the username
"anonymous" and a password of your e-mail address.  After logging in,
type "cd internet-drafts" and then
     "get draft-smith-ipatm-bcast-00.txt".
A URL for the Internet-Draft is:
ftp://ds.internic.net/internet-drafts/draft-smith-ipatm-bcast-00.txt
 
Internet-Drafts directories are located at:	
	                                                
     o  Africa                                   
        Address:  ftp.is.co.za (196.4.160.2)	
	                                                
     o  Europe                                   
        Address:  nic.nordu.net (192.36.148.17)	
        Address:  ftp.nis.garr.it (192.12.192.10)
	                   cd mirrors/internet-drafts   
	                                                
     o  Pacific Rim                              
        Address:  munnari.oz.au (128.250.1.21)	
	                                                
     o  US East Coast                            
        Address:  ds.internic.net (198.49.45.10)	
	                                                
     o  US West Coast                            
        Address:  ftp.isi.edu (128.9.0.32)  	
	                                                
Internet-Drafts are also available by mail.	
	                                                
Send a message to:  mailserv@ds.internic.net. In the body type: 
     "FILE /internet-drafts/draft-smith-ipatm-bcast-00.txt".
							
NOTE: The mail server at ds.internic.net can return the document in
      MIME-encoded form by using the "mpack" utility.  To use this
      feature, insert the command "ENCODING mime" before the "FILE"
      command.  To decode the response(s), you will need "munpack" or
      a MIME-compliant mail reader.  Different MIME-compliant mail readers
      exhibit different behavior, especially when dealing with
      "multipart" MIME messages (i.e., documents which have been split
      up into multiple messages), so check your local documentation on
      how to manipulate these messages.
							
For questions, please mail to Internet-Drafts@cnri.reston.va.us.
							

Below is the data which will enable a MIME compliant mail reader 
implementation to automatically retrieve the ASCII version
of the Internet-Draft.

--NextPart
Content-Type: Multipart/Alternative; Boundary="OtherAccess"

--OtherAccess
Content-Type:  Message/External-body;
        access-type="mail-server";
        server="mailserv@ds.internic.net"

Content-Type: text/plain
Content-ID: <19950424144009.I-D@CNRI.Reston.VA.US>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948568940.21002.10@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0

ENCODING mime
FILE /internet-drafts/draft-smith-ipatm-bcast-00.txt

--OtherAccess
Content-Type:   Message/External-body;
        name="draft-smith-ipatm-bcast-00.txt";
        site="ds.internic.net";
        access-type="anon-ftp";
        directory="internet-drafts"

Content-Type: text/plain
Content-ID: <19950424144009.I-D@CNRI.Reston.VA.US>
Date: Sun, 26 Jan 2014 12:26:34 -0500
Message-Id: <635263359948570390.21002.11@Jeffreys-MacBook-Air.local>
MIME-Version: 1.0


--OtherAccess--

--NextPart--
