X-Andrew-Authenticated-As: 0;bambam.galaxy;The Root of All Evil
Return-Path: <hammer>
Received: from greenbush.bellcore.com by bambam.bellcore.com (4.1/4.7)
	id <AA09071> for andrew; Wed, 3 Jun 92 13:20:09 EDT
Received: from thumper.bellcore.com by greenbush.bellcore.com (4.1/4.7)
	id <AA01104> for andrew@bambam; Wed, 3 Jun 92 13:20:07 EDT
Received: from savage.bellcore.com by thumper.bellcore.com (4.1/4.7)
	id <AA29426> for andrew@greenbush; Wed, 3 Jun 92 13:19:59 EDT
Received: by savage.bellcore.com (4.1/4.7)
	id <AA00616> for localmsgs@thumper; Wed, 3 Jun 92 13:20:02 EDT
Received: from Messages.8.5.N.CUILIB.3.45.SNAP.NOT.LINKED.savage.galaxy.sun4.41
          via MS.5.6.savage.galaxy.sun4_41;
          Wed,  3 Jun 1992 13:20:01 -0400 (EDT)
Message-Id: <8e=Dx1S0M26IE17rlY@thumper.bellcore.com>
Date: Wed,  3 Jun 1992 13:20:01 -0400 (EDT)
From: Tom Brinck <hammer>
X-Andrew-Message-Size: 323+1
Mime-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="Interpart.Boundary.ge=Dx0m0M26IQ17rd0"
To: msgs
Subject: misdirected chinese mail

> THIS IS A MESSAGE IN 'MIME' FORMAT.  Your mail reader does not support MIME.
> Please read the first section, which is plain text, and ignore the rest.

--Interpart.Boundary.ge=Dx0m0M26IQ17rd0
Content-type: text/plain; charset=US-ASCII

I received a magazine in Chinese in the mail (I think from Taiwan).

Here is a picture of the characters that I believe represent the name of
the recipient.  If this is your name, come and get it in room 2A219.
[An Andrew ToolKit view (mailobjv) was included here, but could not be
displayed.]
-- Tom

----------------------------------------------
Tom Brinck
Bellcore
(201) 829-5238
hammer@bellcore.com

--Interpart.Boundary.ge=Dx0m0M26IQ17rd0
Content-Type: multipart/mixed; 
	boundary="Alternative.Boundary.ge=Dx0m0M26II17rZy"

--Alternative.Boundary.ge=Dx0m0M26II17rZy
Content-type: text/richtext; charset=US-ASCII
Content-Transfer-Encoding: quoted-printable

I received a magazine in Chinese in the mail (I think from Taiwan).<nl>
<nl>
Here is a picture of the characters that I believe represent the name of the r=
ecipient.  If this is your name, come and get it in room 2A219.<nl>

--Alternative.Boundary.ge=Dx0m0M26II17rZy
Content-type: image/x-xbm
Content-Description: Push here to see your name
Content-Transfer-Encoding: quoted-printable

#define chinese-name_width 80
#define chinese-name_height 20
static char chinese-name_bits[] =3D {
   0x00, 0x10, 0xa0, 0x20, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0xdf, 0x1f=
,
   0xac, 0xb8, 0x00, 0x08, 0x08, 0x20, 0x00, 0x00, 0x50, 0x00, 0xf8, 0x70=
,
   0x00, 0x08, 0x48, 0x20, 0x00, 0x00, 0x50, 0x08, 0xe0, 0x78, 0x00, 0x48=
,
   0x7f, 0x20, 0x20, 0x00, 0xd1, 0x0f, 0x18, 0x8b, 0x00, 0x7f, 0x14, 0xfe=
,
   0x3f, 0x00, 0x5f, 0x00, 0xf8, 0xff, 0x01, 0x08, 0x72, 0x10, 0x00, 0x00=
,
   0x41, 0x08, 0x04, 0x82, 0x00, 0x08, 0x41, 0x10, 0x00, 0x00, 0xc1, 0x0f=
,
   0x00, 0x02, 0x00, 0x1c, 0x60, 0xf0, 0x0f, 0x00, 0x51, 0x20, 0xfc, 0xff=
,
   0x01, 0x1c, 0x62, 0x28, 0x08, 0x00, 0xdf, 0x3f, 0x00, 0x07, 0x00, 0x2a=
,
   0x22, 0x48, 0x08, 0x00, 0x51, 0x00, 0x00, 0x07, 0x00, 0x2a, 0x32, 0x48=
,
   0x04, 0x00, 0x50, 0x11, 0x80, 0x0b, 0x00, 0x0b, 0x14, 0xc8, 0x02, 0x00=
,
   0x50, 0x1a, 0xc0, 0x0a, 0x00, 0x09, 0x0c, 0x84, 0x01, 0x00, 0x50, 0x0e=
,
   0x40, 0x12, 0x00, 0x09, 0x1c, 0x84, 0x01, 0x00, 0x50, 0x06, 0x20, 0x32=
,
   0x00, 0x08, 0x36, 0x46, 0x02, 0x00, 0x58, 0x19, 0x18, 0xc2, 0x00, 0x08=
,
   0x73, 0x73, 0x0c, 0x00, 0xce, 0x18, 0x00, 0x02, 0x00, 0x88, 0x00, 0x00=
,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00=
,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00=
,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};


--Alternative.Boundary.ge=Dx0m0M26II17rZy
Content-type: text/richtext; charset=US-ASCII
Content-Transfer-Encoding: quoted-printable

<nl>
<nl>
-- Tom<nl>
<nl>
----------------------------------------------<nl>
Tom Brinck<nl>
Bellcore<nl>
(201) 829-5238<nl>
hammer@bellcore.com<nl>

--Alternative.Boundary.ge=Dx0m0M26II17rZy--

--Interpart.Boundary.ge=Dx0m0M26IQ17rd0--
