#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImapClientDemo.Resource", IsApplication=true)]

namespace ImapClientDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int buttonLogin = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int checkSsl = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int listView = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int myButton = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int scrollView = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int textBody = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int textDate = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int textFrom = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int textLogin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textPassword = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int textPort = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int textServer = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int textSubject = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FoldersLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MessageListItemLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MessagesLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewMessageLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
